"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/lib/db/pool";
import { getCurrentSessionUserId } from "@/lib/auth/session";

type AccessRow={customer_id:string;contractor_owner_id:string|null;selected_contractor_id:string|null};
const changeSchema=z.object({projectId:z.string().uuid(),title:z.string().trim().min(3).max(160),reason:z.string().trim().min(5).max(1500),scopeChange:z.string().trim().min(5).max(3000),amountDelta:z.coerce.number().min(-1000000000).max(1000000000),durationDeltaDays:z.coerce.number().int().min(-3650).max(3650)});
const decisionSchema=z.object({projectId:z.string().uuid(),changeOrderId:z.string().uuid(),decision:z.enum(["approved","rejected"]),comment:z.string().trim().max(1500).optional()});
const paymentSchema=z.object({projectId:z.string().uuid(),stageId:z.string().uuid().optional(),amount:z.coerce.number().positive().max(1000000000),paidAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),note:z.string().trim().max(1000).optional()});

export async function createChangeOrder(formData:FormData){
 const p=changeSchema.safeParse({projectId:formData.get("projectId"),title:formData.get("title"),reason:formData.get("reason"),scopeChange:formData.get("scopeChange"),amountDelta:formData.get("amountDelta"),durationDeltaDays:formData.get("durationDeltaDays")});
 if(!p.success)return{success:false,message:p.error.issues[0]?.message??"Проверьте данные"}; const userId=await getCurrentSessionUserId(); if(!userId)return{success:false,message:"Необходимо войти"}; const access=await getAccess(p.data.projectId,userId); if(!access||access.role!=="contractor")return{success:false,message:"Запрос изменения может создать выбранный подрядчик"};
 const client=await db.connect();try{await client.query("BEGIN");const created=await client.query<{id:string}>(`INSERT INTO public.project_change_orders(project_id,requested_by,title,reason,scope_change,amount_delta,duration_delta_days) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[p.data.projectId,userId,p.data.title,p.data.reason,p.data.scopeChange,p.data.amountDelta,p.data.durationDeltaDays]);await insertEvent(client,{projectId:p.data.projectId,authorId:userId,eventType:"change_order_created",title:"Запрошено изменение проекта",description:p.data.title,metadata:{change_order_id:created.rows[0]?.id,amount_delta:p.data.amountDelta,duration_delta_days:p.data.durationDeltaDays}});await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");console.error("Ошибка создания change order:",e);return{success:false,message:"Не удалось создать запрос изменения"}}finally{client.release()} revalidate(p.data.projectId);return{success:true,message:"Изменение отправлено заказчику на согласование"};
}
export async function decideChangeOrder(formData:FormData){
 const p=decisionSchema.safeParse({projectId:formData.get("projectId"),changeOrderId:formData.get("changeOrderId"),decision:formData.get("decision"),comment:formData.get("comment")||undefined});if(!p.success)return{success:false,message:"Некорректное решение"};const userId=await getCurrentSessionUserId();if(!userId)return{success:false,message:"Необходимо войти"};const access=await getAccess(p.data.projectId,userId);if(!access||access.role!=="customer")return{success:false,message:"Согласовать изменение может только заказчик"};
 const client=await db.connect();try{await client.query("BEGIN");const r=await client.query<{title:string;amount_delta:string|number;duration_delta_days:number}>(`UPDATE public.project_change_orders SET status=$1,decision_comment=$2,decided_by=$3,decided_at=now(),updated_at=now() WHERE id=$4 AND project_id=$5 AND status='pending' RETURNING title,amount_delta,duration_delta_days`,[p.data.decision,p.data.comment??null,userId,p.data.changeOrderId,p.data.projectId]);const c=r.rows[0];if(!c){await client.query("ROLLBACK");return{success:false,message:"Изменение уже обработано или не найдено"}}await insertEvent(client,{projectId:p.data.projectId,authorId:userId,eventType:p.data.decision==="approved"?"change_order_approved":"change_order_rejected",title:p.data.decision==="approved"?"Изменение согласовано":"Изменение отклонено",description:c.title,metadata:{change_order_id:p.data.changeOrderId,amount_delta:Number(c.amount_delta),duration_delta_days:c.duration_delta_days}});await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");console.error("Ошибка решения change order:",e);return{success:false,message:"Не удалось сохранить решение"}}finally{client.release()}revalidate(p.data.projectId);return{success:true,message:p.data.decision==="approved"?"Изменение согласовано":"Изменение отклонено"};
}
export async function cancelChangeOrder(formData:FormData){const projectId=String(formData.get("projectId")??"");const changeOrderId=String(formData.get("changeOrderId")??"");const userId=await getCurrentSessionUserId();if(!userId)return{success:false,message:"Необходимо войти"};const access=await getAccess(projectId,userId);if(!access||access.role!=="contractor")return{success:false,message:"Нет доступа"};const r=await db.query(`UPDATE public.project_change_orders SET status='cancelled',updated_at=now() WHERE id=$1 AND project_id=$2 AND requested_by=$3 AND status='pending' RETURNING id`,[changeOrderId,projectId,userId]);if(!r.rowCount)return{success:false,message:"Изменение нельзя отменить"};revalidate(projectId);return{success:true,message:"Запрос изменения отменён"}}

export async function recordProjectPayment(formData:FormData){
 const rawStage=String(formData.get("stageId")??"").trim();const p=paymentSchema.safeParse({projectId:formData.get("projectId"),stageId:rawStage||undefined,amount:formData.get("amount"),paidAt:formData.get("paidAt"),note:formData.get("note")||undefined});if(!p.success)return{success:false,message:"Проверьте сумму, этап и дату платежа"};const userId=await getCurrentSessionUserId();if(!userId)return{success:false,message:"Необходимо войти"};const access=await getAccess(p.data.projectId,userId);if(!access||access.role!=="customer")return{success:false,message:"Платежи фиксирует заказчик"};
 const client=await db.connect();try{await client.query("BEGIN");const budget=await client.query<{contract_total:string|number;paid_total:string|number}>(`SELECT COALESCE(pb.price,0)+COALESCE((SELECT SUM(amount_delta) FROM public.project_change_orders WHERE project_id=p.id AND status='approved'),0) AS contract_total,COALESCE((SELECT SUM(amount) FROM public.project_payments WHERE project_id=p.id),0) AS paid_total FROM public.projects p LEFT JOIN public.project_bids pb ON pb.id=p.selected_bid_id WHERE p.id=$1 FOR UPDATE OF p`,[p.data.projectId]);const b=budget.rows[0];if(!b)throw new Error("Project not found");const remaining=Number(b.contract_total)-Number(b.paid_total);if(p.data.amount>remaining+0.005){await client.query("ROLLBACK");return{success:false,message:"Платёж превышает остаток согласованного бюджета"}}if(p.data.stageId){const stage=await client.query<{planned:string|number;paid:string|number}>(`SELECT COALESCE(ps.payment_due_amount,(COALESCE(ps.payment_due_percent,0)/100.0)*$2,ps.price,0) AS planned,COALESCE((SELECT SUM(pp.amount) FROM public.project_payments pp WHERE pp.stage_id=ps.id),0) AS paid FROM public.project_stages ps WHERE ps.id=$1 AND ps.project_id=$3`,[p.data.stageId,Number(b.contract_total),p.data.projectId]);const s=stage.rows[0];if(!s){await client.query("ROLLBACK");return{success:false,message:"Этап не найден"}}if(p.data.amount>Number(s.planned)-Number(s.paid)+0.005){await client.query("ROLLBACK");return{success:false,message:"Платёж превышает остаток по выбранному этапу"}}}
 const r=await client.query<{id:string}>(`INSERT INTO public.project_payments(project_id,recorded_by,stage_id,amount,paid_at,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[p.data.projectId,userId,p.data.stageId??null,p.data.amount,p.data.paidAt,p.data.note??null]);await insertEvent(client,{projectId:p.data.projectId,authorId:userId,eventType:"payment_recorded",title:"Зафиксирован платёж",description:p.data.note??null,metadata:{payment_id:r.rows[0]?.id,stage_id:p.data.stageId??null,amount:p.data.amount,paid_at:p.data.paidAt}});await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");console.error("Ошибка записи платежа:",e);return{success:false,message:"Не удалось добавить платёж"}}finally{client.release()}revalidate(p.data.projectId);return{success:true,message:"Платёж добавлен"};
}
async function getAccess(projectId:string,userId:string){const r=await db.query<AccessRow>(`SELECT p.customer_id,p.selected_contractor_id,cc.owner_id AS contractor_owner_id FROM public.projects p LEFT JOIN public.contractor_companies cc ON cc.id=p.selected_contractor_id WHERE p.id=$1 LIMIT 1`,[projectId]);const row=r.rows[0];if(!row||!row.selected_contractor_id)return null;if(row.customer_id===userId)return{role:"customer" as const};if(row.contractor_owner_id===userId)return{role:"contractor" as const};return null}
async function insertEvent(client:{query:(text:string,values?:unknown[])=>Promise<unknown>},input:{projectId:string;authorId:string;eventType:string;title:string;description:string|null;metadata:Record<string,unknown>}){await client.query(`INSERT INTO public.project_events(project_id,author_id,event_type,title,description,metadata) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[input.projectId,input.authorId,input.eventType,input.title,input.description,JSON.stringify(input.metadata)])}
function revalidate(projectId:string){revalidatePath(`/customer/work/${projectId}/changes`);revalidatePath(`/contractor/work/${projectId}/changes`);revalidatePath(`/customer/work/${projectId}`);revalidatePath(`/contractor/work/${projectId}`)}
