"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/lib/db/pool";
import { getCurrentSessionUserId } from "@/lib/auth/session";

const openSchema=z.object({projectId:z.string().uuid(),subject:z.string().trim().min(3).max(180),description:z.string().trim().min(10).max(5000),stageId:z.string().uuid().optional(),changeOrderId:z.string().uuid().optional(),paymentId:z.string().uuid().optional()});
const messageSchema=z.object({projectId:z.string().uuid(),disputeId:z.string().uuid(),body:z.string().trim().min(1).max(5000)});
const statusSchema=z.object({projectId:z.string().uuid(),disputeId:z.string().uuid(),status:z.enum(["under_review","resolved","closed"]),resolution:z.string().trim().max(5000).optional()});

export async function openProjectDispute(formData:FormData){const parsed=openSchema.safeParse({projectId:formData.get("projectId"),subject:formData.get("subject"),description:formData.get("description"),stageId:optional(formData.get("stageId")),changeOrderId:optional(formData.get("changeOrderId")),paymentId:optional(formData.get("paymentId"))});if(!parsed.success)return{success:false,message:parsed.error.issues[0]?.message??"Проверьте данные"};const userId=await getCurrentSessionUserId();if(!userId)return{success:false,message:"Необходимо войти"};if(!await hasAccess(parsed.data.projectId,userId))return{success:false,message:"Нет доступа"};const client=await db.connect();try{await client.query("BEGIN");const r=await client.query<{id:string}>(`INSERT INTO public.project_disputes(project_id,opened_by,stage_id,change_order_id,payment_id,subject,description) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[parsed.data.projectId,userId,parsed.data.stageId??null,parsed.data.changeOrderId??null,parsed.data.paymentId??null,parsed.data.subject,parsed.data.description]);await audit(client,parsed.data.projectId,userId,"dispute_opened","dispute",r.rows[0]?.id??null,{subject:parsed.data.subject});await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");console.error("Ошибка открытия спора:",e);return{success:false,message:"Не удалось открыть спор"}}finally{client.release()}refresh(parsed.data.projectId);return{success:true,message:"Спор открыт"}}

export async function addDisputeMessage(formData:FormData){const p=messageSchema.safeParse({projectId:formData.get("projectId"),disputeId:formData.get("disputeId"),body:formData.get("body")});if(!p.success)return{success:false,message:"Введите сообщение"};const userId=await getCurrentSessionUserId();if(!userId||!await hasAccess(p.data.projectId,userId))return{success:false,message:"Нет доступа"};const r=await db.query<{id:string}>(`INSERT INTO public.project_dispute_messages(dispute_id,author_id,body) SELECT d.id,$3,$4 FROM public.project_disputes d WHERE d.id=$1 AND d.project_id=$2 RETURNING id`,[p.data.disputeId,p.data.projectId,userId,p.data.body]);if(!r.rowCount)return{success:false,message:"Спор не найден"};await db.query(`INSERT INTO public.project_audit_log(project_id,actor_id,action,entity_type,entity_id,payload) VALUES($1,$2,'dispute_message_added','dispute',$3,$4::jsonb)`,[p.data.projectId,userId,p.data.disputeId,JSON.stringify({message_id:r.rows[0]?.id})]);refresh(p.data.projectId);return{success:true,message:"Сообщение добавлено"}}

export async function updateDisputeStatus(formData:FormData){const p=statusSchema.safeParse({projectId:formData.get("projectId"),disputeId:formData.get("disputeId"),status:formData.get("status"),resolution:optional(formData.get("resolution"))});if(!p.success)return{success:false,message:"Проверьте решение"};const userId=await getCurrentSessionUserId();if(!userId||!await hasAccess(p.data.projectId,userId))return{success:false,message:"Нет доступа"};if(p.data.status==="resolved"&&!p.data.resolution)return{success:false,message:"Для разрешения спора укажите итог"};const r=await db.query(`UPDATE public.project_disputes SET status=$1,resolution=CASE WHEN $1='resolved' THEN $2 ELSE resolution END,resolved_by=CASE WHEN $1='resolved' THEN $3 ELSE resolved_by END,resolved_at=CASE WHEN $1='resolved' THEN now() ELSE resolved_at END,updated_at=now() WHERE id=$4 AND project_id=$5 RETURNING id`,[p.data.status,p.data.resolution??null,userId,p.data.disputeId,p.data.projectId]);if(!r.rowCount)return{success:false,message:"Спор не найден"};await db.query(`INSERT INTO public.project_audit_log(project_id,actor_id,action,entity_type,entity_id,payload) VALUES($1,$2,'dispute_status_changed','dispute',$3,$4::jsonb)`,[p.data.projectId,userId,p.data.disputeId,JSON.stringify({status:p.data.status,resolution:p.data.resolution??null})]);refresh(p.data.projectId);return{success:true,message:"Статус спора обновлён"}}

async function hasAccess(projectId:string,userId:string){const r=await db.query(`SELECT 1 FROM public.projects p LEFT JOIN public.contractor_companies cc ON cc.id=p.selected_contractor_id WHERE p.id=$1 AND (p.customer_id=$2 OR cc.owner_id=$2)`,[projectId,userId]);return Boolean(r.rowCount)}
async function audit(client:{query:(q:string,v?:unknown[])=>Promise<unknown>},projectId:string,actorId:string,action:string,entityType:string,entityId:string|null,payload:Record<string,unknown>){await client.query(`INSERT INTO public.project_audit_log(project_id,actor_id,action,entity_type,entity_id,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[projectId,actorId,action,entityType,entityId,JSON.stringify(payload)])}
function optional(v:FormDataEntryValue|null){const s=String(v??"").trim();return s||undefined}
function refresh(id:string){revalidatePath(`/customer/work/${id}/disputes`);revalidatePath(`/contractor/work/${id}/disputes`)}
