import {db} from "@/lib/db/pool";
import {requireActiveUser} from "@/lib/auth/require-active-user";

type Row={project_title:string;customer_id:string;contractor_owner_id:string|null;version_no:number;title:string;body:string;customer_approved_at:Date|string|null;contractor_approved_at:Date|string|null};
export async function GET(request:Request,{params}:{params:Promise<{projectId:string}>}){const auth=await requireActiveUser();if(!auth.success)return new Response("Требуется авторизация",{status:401});const{projectId}=await params;const url=new URL(request.url);const requested=Number(url.searchParams.get("version")||0);const result=await db.query<Row>(`SELECT p.title AS project_title,p.customer_id,cc.owner_id AS contractor_owner_id,v.version_no,v.title,v.body,v.customer_approved_at,v.contractor_approved_at FROM public.projects p LEFT JOIN public.contractor_companies cc ON cc.id=p.selected_contractor_id JOIN public.project_contracts pc ON pc.project_id=p.id JOIN public.project_contract_versions v ON v.contract_id=pc.id AND v.version_no=CASE WHEN $2>0 THEN $2 ELSE pc.current_version END WHERE p.id=$1::uuid LIMIT 1`,[projectId,requested]);const row=result.rows[0];if(!row)return new Response("Договор не найден",{status:404});if(row.customer_id!==auth.user.id&&row.contractor_owner_id!==auth.user.id)return new Response("Нет доступа",{status:403});const documentText=`${row.title}\n\n${row.body}\n\nЭЛЕКТРОННОЕ СОГЛАСОВАНИЕ\nЗаказчик: ${row.customer_approved_at?`подписано ${formatDate(row.customer_approved_at)}`:"подпись отсутствует"}\nПодрядчик: ${row.contractor_approved_at?`подписано ${formatDate(row.contractor_approved_at)}`:"подпись отсутствует"}\nВерсия договора: ${row.version_no}`;const bytes=buildDocx(documentText,row.title);const filename=safeFilename(`Договор-${row.project_title}-версия-${row.version_no}.docx`);return new Response(bytes,{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(filename)}`,"Cache-Control":"private, no-store"}})}
function formatDate(value:Date|string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Moscow"}).format(new Date(value))}
function safeFilename(value:string){return value.replace(/[\\/:*?"<>|]/g,"-").slice(0,140)}
function buildDocx(text:string,title:string){const paragraphs=text.split(/\r?\n/).map(line=>`<w:p><w:r><w:t xml:space="preserve">${xml(line||" ")}</w:t></w:r></w:p>`).join("");const entries=[
 {name:"[Content_Types].xml",data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`},
 {name:"_rels/.rels",data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`},
 {name:"word/document.xml",data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`},
 {name:"word/_rels/document.xml.rels",data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>`},
 {name:"docProps/core.xml",data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${xml(title)}</dc:title><dc:creator>СтройВыбор</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">${new Date().toISOString()}</dcterms:created></cp:coreProperties>`},
 {name:"docProps/app.xml",data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>СтройВыбор</Application></Properties>`}
 ];return zipStore(entries)}
function xml(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function zipStore(entries:Array<{name:string;data:string}>){const local:Buffer[]=[];const central:Buffer[]=[];let offset=0;for(const entry of entries){const name=Buffer.from(entry.name,"utf8");const data=Buffer.from(entry.data,"utf8");const crc=crc32(data);const localHeader=Buffer.alloc(30);localHeader.writeUInt32LE(0x04034b50,0);localHeader.writeUInt16LE(20,4);localHeader.writeUInt16LE(0x0800,6);localHeader.writeUInt16LE(0,8);localHeader.writeUInt16LE(0,10);localHeader.writeUInt16LE(0,12);localHeader.writeUInt32LE(crc,14);localHeader.writeUInt32LE(data.length,18);localHeader.writeUInt32LE(data.length,22);localHeader.writeUInt16LE(name.length,26);localHeader.writeUInt16LE(0,28);local.push(localHeader,name,data);const centralHeader=Buffer.alloc(46);centralHeader.writeUInt32LE(0x02014b50,0);centralHeader.writeUInt16LE(20,4);centralHeader.writeUInt16LE(20,6);centralHeader.writeUInt16LE(0x0800,8);centralHeader.writeUInt16LE(0,10);centralHeader.writeUInt16LE(0,12);centralHeader.writeUInt16LE(0,14);centralHeader.writeUInt32LE(crc,16);centralHeader.writeUInt32LE(data.length,20);centralHeader.writeUInt32LE(data.length,24);centralHeader.writeUInt16LE(name.length,28);centralHeader.writeUInt16LE(0,30);centralHeader.writeUInt16LE(0,32);centralHeader.writeUInt16LE(0,34);centralHeader.writeUInt16LE(0,36);centralHeader.writeUInt32LE(0,38);centralHeader.writeUInt32LE(offset,42);central.push(centralHeader,name);offset+=localHeader.length+name.length+data.length}const centralData=Buffer.concat(central);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(centralData.length,12);end.writeUInt32LE(offset,16);end.writeUInt16LE(0,20);return Buffer.concat([...local,centralData,end])}
let table:Uint32Array|undefined;function crc32(buffer:Buffer){if(!table){table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}}let crc=0xffffffff;for(const byte of buffer)crc=table[(crc^byte)&0xff]^(crc>>>8);return(crc^0xffffffff)>>>0}
