import {timingSafeEqual} from "node:crypto";
import {db} from "@/lib/db/pool";
import {getAppBaseUrl,sendTransactionalEmail} from "@/lib/email/send-transactional-email";

export const dynamic="force-dynamic";
export const maxDuration=60;

export async function GET(request:Request){if(!authorized(request))return Response.json({ok:false},{status:401});try{await db.query("SELECT public.stroyselect_housekeeping()");const reminders=await createDueReminders();const email=await deliverQueuedEmail();return Response.json({ok:true,reminders,email,ranAt:new Date().toISOString()},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("Scheduled maintenance failed",error);return Response.json({ok:false,message:"Не удалось выполнить обслуживание"},{status:500,headers:{"Cache-Control":"no-store"}})}}

function authorized(request:Request){const secret=process.env.CRON_SECRET?.trim();if(!secret)return false;const header=request.headers.get("authorization")??"";const candidate=header.startsWith("Bearer ")?header.slice(7):"";const a=Buffer.from(secret);const b=Buffer.from(candidate);return a.length===b.length&&timingSafeEqual(a,b)}

async function createDueReminders(){let created=0;const appointments=await db.query<{id:string;project_id:string;title:string;scheduled_start:Date|string;customer_id:string;contractor_user_id:string|null}>(`SELECT pa.id,pa.project_id,pa.title,pa.scheduled_start,p.customer_id,cc.owner_id AS contractor_user_id FROM public.project_appointments pa JOIN public.projects p ON p.id=pa.project_id LEFT JOIN public.contractor_companies cc ON cc.id=p.selected_contractor_id WHERE pa.reminder_at IS NOT NULL AND pa.reminder_at<=now() AND pa.reminder_sent_at IS NULL AND pa.status IN ('proposed','confirmed') ORDER BY pa.reminder_at ASC LIMIT 100`);for(const row of appointments.rows){for(const userId of [row.customer_id,row.contractor_user_id].filter((v):v is string=>Boolean(v))){if(await insertNotification({userId,projectId:row.project_id,type:"appointment_reminder",title:"Напоминание о встрече",body:`«${row.title}» запланирована на ${new Date(row.scheduled_start).toLocaleString("ru-RU",{timeZone:"Europe/Moscow"})}`,url:userId===row.customer_id?`/customer/work/${row.project_id}/appointments`:`/contractor/work/${row.project_id}/appointments`,key:`appointment-reminder:${row.id}:${userId}`}))created++}await db.query(`UPDATE public.project_appointments SET reminder_sent_at=now(),updated_at=now() WHERE id=$1::uuid`,[row.id])}
const stages=await db.query<{id:string;project_id:string;title:string;planned_end_date:Date|string;customer_id:string;contractor_user_id:string|null}>(`SELECT ps.id,ps.project_id,ps.title,ps.planned_end_date,p.customer_id,cc.owner_id AS contractor_user_id FROM public.project_stages ps JOIN public.projects p ON p.id=ps.project_id LEFT JOIN public.contractor_companies cc ON cc.id=p.selected_contractor_id WHERE ps.planned_end_date IS NOT NULL AND ps.status NOT IN ('completed','cancelled') AND ps.planned_end_date<=current_date+1 AND (ps.due_reminder_sent_at IS NULL OR (ps.planned_end_date<current_date AND ps.overdue_notified_at IS NULL)) ORDER BY ps.planned_end_date ASC LIMIT 100`);for(const row of stages.rows){const end=new Date(row.planned_end_date);const overdue=end.getTime()<Date.now()-24*60*60*1000;for(const userId of [row.customer_id,row.contractor_user_id].filter((v):v is string=>Boolean(v))){if(await insertNotification({userId,projectId:row.project_id,type:overdue?"stage_overdue":"stage_due_soon",title:overdue?"Этап просрочен":"Срок этапа приближается",body:`Этап «${row.title}»: плановая дата завершения ${end.toLocaleDateString("ru-RU")}.`,url:userId===row.customer_id?`/customer/work/${row.project_id}`:`/contractor/work/${row.project_id}`,key:`stage-${overdue?"overdue":"due"}:${row.id}:${userId}`}))created++}await db.query(`UPDATE public.project_stages SET due_reminder_sent_at=COALESCE(due_reminder_sent_at,now()),overdue_notified_at=CASE WHEN $2 THEN COALESCE(overdue_notified_at,now()) ELSE overdue_notified_at END,updated_at=now() WHERE id=$1::uuid`,[row.id,overdue])}return created}

async function insertNotification(input:{userId:string;projectId:string;type:string;title:string;body:string;url:string;key:string}){const result=await db.query<{id:string}>(`INSERT INTO public.notifications(user_id,notification_type,title,body,project_id,url,metadata,deduplication_key) VALUES($1::uuid,$2,$3,$4,$5::uuid,$6,'{}'::jsonb,$7) ON CONFLICT DO NOTHING RETURNING id`,[input.userId,input.type,input.title,input.body,input.projectId,input.url,input.key]);const id=result.rows[0]?.id;if(!id)return false;const pref=await db.query<{email_enabled:boolean;email:string|null}>(`SELECT COALESCE(np.email_enabled,true) AS email_enabled,p.email FROM public.profiles p LEFT JOIN public.notification_preferences np ON np.user_id=p.id WHERE p.id=$1::uuid`,[input.userId]);const settings=pref.rows[0];if(settings?.email_enabled&&settings.email)await db.query(`INSERT INTO public.notification_delivery_queue(notification_id,channel,recipient) VALUES($1::uuid,'email',$2) ON CONFLICT DO NOTHING`,[id,settings.email]);return true}

async function deliverQueuedEmail(){const rows=await db.query<{id:string;recipient:string;attempts:number;title:string;body:string|null;url:string|null}>(`SELECT q.id,q.recipient,q.attempts,n.title,n.body,n.url FROM public.notification_delivery_queue q JOIN public.notifications n ON n.id=q.notification_id WHERE q.status IN ('pending','failed') AND q.next_attempt_at<=now() AND q.attempts<6 ORDER BY q.created_at ASC LIMIT 50`);let sent=0,failed=0;for(const row of rows.rows){await db.query(`UPDATE public.notification_delivery_queue SET status='processing',attempts=attempts+1 WHERE id=$1::uuid`,[row.id]);try{const link=row.url?`${getAppBaseUrl()}${row.url}`:null;const html=`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto"><h2>${escapeHtml(row.title)}</h2>${row.body?`<p>${escapeHtml(row.body)}</p>`:""}${link?`<p><a href="${escapeHtml(link)}">Открыть в СтройВыбор</a></p>`:""}<p style="color:#777;font-size:12px">Это автоматическое уведомление СтройВыбор.</p></div>`;const response=await sendTransactionalEmail({to:row.recipient,subject:row.title,html});if(!response.success)throw new Error(response.message);await db.query(`UPDATE public.notification_delivery_queue SET status='sent',sent_at=now(),last_error=NULL WHERE id=$1::uuid`,[row.id]);sent++}catch(error){const delay=Math.min(360,Math.max(5,2**Math.min(8,Number(row.attempts)||0)));await db.query(`UPDATE public.notification_delivery_queue SET status='failed',last_error=$2,next_attempt_at=now()+($3::text||' minutes')::interval WHERE id=$1::uuid`,[row.id,error instanceof Error?error.message:String(error),delay]);failed++}}return{sent,failed}}
function escapeHtml(value:string){return value.replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]??ch))}
