import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, CheckCircle2, Hammer, MessageSquareText, ShieldCheck, Star, UsersRound } from "lucide-react";
import { AdSlot } from "@/features/ads/components/ad-slot";

export default function HomePage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-40 border-b border-border/70 bg-background/85 backdrop-blur-xl">
        <div className="app-container flex min-h-16 items-center justify-between gap-5 sm:min-h-20">
          <Link href="/" className="text-xl font-black tracking-[-0.05em] sm:text-2xl">StroySelect</Link>
          <nav className="flex items-center gap-2 sm:gap-3" aria-label="Основная навигация">
            <Link href="/login" className="hidden min-h-10 items-center rounded-xl px-4 text-sm font-semibold text-muted-foreground transition hover:bg-secondary hover:text-foreground sm:inline-flex">Войти</Link>
            <Link href="/register" className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground shadow-sm transition hover:-translate-y-0.5 hover:bg-[#5c3b2a] sm:px-5">Начать<ArrowRight className="h-4 w-4" /></Link>
          </nav>
        </div>
      </header>
      <section className="relative overflow-hidden border-b border-border">
        <div className="pointer-events-none absolute -left-48 top-0 h-[520px] w-[520px] rounded-full bg-primary/10 blur-3xl" />
        <div className="pointer-events-none absolute -right-56 top-20 h-[620px] w-[620px] rounded-full bg-secondary blur-3xl" />
        <div className="app-container relative grid items-center gap-12 py-14 sm:py-20 lg:min-h-[700px] lg:grid-cols-[minmax(0,1fr)_minmax(420px,520px)] lg:py-24">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/5 px-3.5 py-2 text-xs font-bold text-primary sm:text-sm"><ShieldCheck className="h-4 w-4" />Проверенные подрядчики</div>
            <h1 className="mt-6 text-4xl font-black leading-[1.03] tracking-[-0.055em] sm:text-5xl lg:text-7xl">Решайте задачи по дому и строительству без лишней суеты</h1>
            <p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">Опишите задачу, сравните предложения и выберите исполнителя. Дальше — договорённости, этапы, документы и контроль в одном месте.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Link href="/register" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-primary px-6 font-bold text-primary-foreground shadow-[0_16px_36px_rgba(107,70,50,0.22)] transition hover:-translate-y-0.5 hover:bg-[#5c3b2a]">Создать задачу<ArrowRight className="h-4 w-4" /></Link>
              <Link href="/register" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl border border-border bg-card px-6 font-bold transition hover:-translate-y-0.5 hover:border-primary/20 hover:bg-secondary/60">Я подрядчик<Hammer className="h-4 w-4" /></Link>
            </div>
            <div className="mt-8 grid max-w-2xl gap-3 sm:grid-cols-3"><HeroFact text="Сравнение предложений" /><HeroFact text="Контроль этапов" /><HeroFact text="Чат и документы" /></div>
          </div>
          <HeroPreview />
        </div>
      </section>
      <AdSlot placement="home_premium" className="app-container pt-7" />
      <section className="app-container py-16 sm:py-20">
        <div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.14em] text-primary">Как это работает</p><h2 className="mt-2 text-3xl font-black tracking-[-0.045em] sm:text-4xl">Один понятный путь от задачи до результата</h2><p className="mt-4 text-sm leading-7 text-muted-foreground sm:text-base">Мы убираем лишние шаги, но сохраняем все важные данные и действия проекта.</p></div>
        <div className="mt-8 grid gap-4 md:grid-cols-3"><StepCard number="01" icon={<Building2 className="h-5 w-5" />} title="Опишите задачу" description="Что нужно сделать, где находится объект, бюджет и желаемые сроки." /><StepCard number="02" icon={<UsersRound className="h-5 w-5" />} title="Сравните исполнителей" description="Смотрите цену, сроки, профиль, опыт и условия в одном формате." /><StepCard number="03" icon={<CheckCircle2 className="h-5 w-5" />} title="Контролируйте результат" description="Работа проходит по этапам с файлами, чатом и фиксацией решений." /></div>
      </section>
      <section className="border-y border-border bg-secondary/25"><div className="app-container py-16 sm:py-20"><div className="grid gap-5 lg:grid-cols-2"><AudienceCard eyebrow="Для заказчика" title="Не ищите по знакомым — сравнивайте" description="Разместите задачу и принимайте решение на основе понятных параметров, а не переписок в десятках чатов." icon={<Building2 className="h-6 w-6" />} buttonText="Создать задачу" features={["Предложения в одном списке","Проверяемые профили","Этапы и приёмка","Документы и чат"]} /><AudienceCard eyebrow="Для подрядчика" title="Получайте заказы, которые вам подходят" description="Покажите специализации и опыт, находите подходящие проекты и ведите работу в одном кабинете." icon={<Hammer className="h-6 w-6" />} buttonText="Стать подрядчиком" features={["Проекты по специализации","Профиль компании","Предложения заказчику","Управление объектами"]} /></div></div></section>
      <section className="app-container py-16 sm:py-20"><div className="grid gap-4 md:grid-cols-3"><TrustCard icon={<BadgeCheck className="h-5 w-5" />} title="Проверка профилей" description="Статусы и данные подрядчиков видны до принятия решения." /><TrustCard icon={<MessageSquareText className="h-5 w-5" />} title="Все договорённости рядом" description="Переписка, файлы и события остаются в рабочем пространстве проекта." /><TrustCard icon={<Star className="h-5 w-5" />} title="История и репутация" description="После работы заказчик может оставить оценку качества, сроков и общения." /></div></section>
      <section className="app-container pb-16 sm:pb-20"><div className="relative overflow-hidden rounded-[2rem] bg-primary p-7 text-primary-foreground shadow-[0_26px_70px_rgba(107,70,50,0.2)] sm:p-10 lg:p-12"><div className="pointer-events-none absolute -right-24 -top-24 h-80 w-80 rounded-full bg-white/10 blur-3xl" /><div className="relative flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.14em] text-primary-foreground/65">StroySelect</p><h2 className="mt-3 text-3xl font-black tracking-[-0.04em] sm:text-4xl">Начните с одной задачи</h2><p className="mt-3 max-w-xl text-sm leading-7 text-primary-foreground/75 sm:text-base">От мелкого ремонта до крупного проекта — путь начинается одинаково: с понятного описания задачи.</p></div><Link href="/register" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-2xl bg-white px-6 font-bold text-primary transition hover:-translate-y-0.5">Создать аккаунт<ArrowRight className="h-4 w-4" /></Link></div></div></section>
      <footer className="border-t border-border"><div className="app-container flex flex-col gap-2 py-7 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><p className="font-black text-foreground">StroySelect</p><p>Для заказчиков и подрядчиков</p></div></footer>
    </main>
  );
}
function HeroFact({ text }: { text: string }) { return <div className="flex items-center gap-2 rounded-xl border border-border bg-card/75 px-3 py-3 text-xs font-semibold shadow-sm"><CheckCircle2 className="h-4 w-4 text-primary" /><span>{text}</span></div>; }
function HeroPreview() { return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-6 rounded-[2.5rem] bg-primary/10 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-border bg-card p-5 shadow-[0_30px_90px_rgba(55,35,24,0.16)] sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-[11px] font-semibold text-muted-foreground">Рабочее пространство</p><p className="mt-1 text-base font-black">Ремонт квартиры</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-[11px] font-bold text-primary">В работе</span></div><div className="mt-5 rounded-[1.35rem] bg-secondary/65 p-5"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] text-muted-foreground">Прогресс</p><p className="mt-1 text-3xl font-black text-primary">65%</p></div><p className="text-[11px] text-muted-foreground">3 из 5 этапов</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-background"><div className="h-full w-[65%] rounded-full bg-primary" /></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><PreviewCard title="Предложения" value="7" note="подрядчиков" /><PreviewCard title="Бюджет" value="320 000 ₽" note="принятое предложение" /></div><div className="mt-4 rounded-[1.35rem] border border-border p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-muted-foreground">Текущий этап</p><p className="mt-2 font-black">Электромонтаж</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><CheckCircle2 className="h-5 w-5" /></span></div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-muted-foreground">Следующее действие</span><span className="font-bold text-primary">Приёмка</span></div></div></div></div>; }
function PreviewCard({ title, value, note }: { title: string; value: string; note: string }) { return <div className="rounded-[1.2rem] border border-border bg-background/70 p-4"><p className="text-[11px] text-muted-foreground">{title}</p><p className="mt-2 text-xl font-black tracking-[-0.03em]">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{note}</p></div>; }
function StepCard({ number, icon, title, description }: { number: string; icon: React.ReactNode; title: string; description: string }) { return <article className="rounded-[1.5rem] border border-border bg-card p-5 shadow-[var(--shadow-soft)] sm:p-6"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-secondary text-primary">{icon}</div><span className="text-sm font-black text-primary/35">{number}</span></div><h3 className="mt-5 text-lg font-black sm:text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></article>; }
function AudienceCard({ eyebrow, title, description, icon, buttonText, features }: { eyebrow: string; title: string; description: string; icon: React.ReactNode; buttonText: string; features: string[] }) { return <article className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] sm:p-7"><div className="flex items-start justify-between gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-secondary text-primary">{icon}</span><span className="rounded-full bg-muted px-3 py-1 text-[11px] font-bold text-muted-foreground">{eyebrow}</span></div><h3 className="mt-6 text-2xl font-black tracking-[-0.03em]">{title}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-muted-foreground">{description}</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{features.map((feature) => <div key={feature} className="flex items-center gap-2 rounded-xl bg-muted/65 px-3 py-3 text-xs font-semibold"><CheckCircle2 className="h-4 w-4 shrink-0 text-primary" />{feature}</div>)}</div><Link href="/register" className="mt-6 inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground transition hover:-translate-y-0.5 hover:bg-[#5c3b2a]">{buttonText}<ArrowRight className="h-4 w-4" /></Link></article>; }
function TrustCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <article className="rounded-[1.5rem] border border-border bg-card p-5 shadow-[var(--shadow-soft)]"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-primary">{icon}</div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></article>; }
