import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, CalendarDays, FolderKanban, MapPin, Plus, Wallet } from "lucide-react";
import { getCurrentProfile } from "@/lib/auth/get-current-profile";
import { getMyProjects } from "@/features/projects/queries/get-my-projects";

export default async function CustomerProjectsPage(){
 const {profile}=await getCurrentProfile();if(profile.role!=="customer")redirect("/dashboard");const projects=await getMyProjects();
 return <main className="min-h-screen bg-background"><div className="app-container py-8 md:py-12"><section className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-primary">Кабинет заказчика</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.035em] md:text-5xl">Мои проекты</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground md:text-base">Управляйте черновиками, опубликованными проектами, предложениями подрядчиков и объектами в работе.</p></div><Link href="/customer/projects/new" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-primary px-5 font-semibold text-primary-foreground"><Plus className="h-5 w-5"/>Создать проект</Link></section>
 {projects.length===0?<EmptyProjects/>:<section className="mt-8 grid gap-5 xl:grid-cols-2">{projects.map(project=><Link key={project.id} href={`/customer/projects/${project.id}`} className="group block min-w-0 overflow-hidden rounded-[1.75rem] border border-border bg-card shadow-[var(--shadow-soft)] transition duration-200 hover:-translate-y-1 hover:border-primary/25 hover:shadow-[var(--shadow-card)]"><div className="min-w-0 p-6 md:p-7"><div className="flex min-w-0 items-start justify-between gap-5"><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold text-primary">{getCategoryName(project.service_categories)}</p><h2 className="mt-2 line-clamp-2 break-words text-xl font-bold tracking-tight md:text-2xl">{project.title}</h2><div className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4 shrink-0"/><span className="truncate">{project.city||"Город не указан"}</span></div></div><div className="flex shrink-0 flex-col items-end gap-3"><ProjectStatusBadge status={project.status}/><div className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-primary transition group-hover:bg-primary group-hover:text-primary-foreground"><ArrowRight className="h-4 w-4"/></div></div></div><p className="mt-5 line-clamp-3 break-words text-sm leading-6 text-muted-foreground">{project.description}</p><div className="my-6 h-px bg-border"/><div className="grid gap-3 sm:grid-cols-3"><InfoItem icon={<Wallet className="h-4 w-4"/>} label="Бюджет" value={formatBudget(project.budget_min,project.budget_max)}/><InfoItem icon={<CalendarDays className="h-4 w-4"/>} label="Создан" value={formatDateTime(project.created_at)??"—"}/><InfoItem icon={<CalendarDays className="h-4 w-4"/>} label="Опубликован" value={formatDateTime(project.published_at)??"Не опубликован"}/></div></div></Link>)}</section>}
 </div></main>}
function EmptyProjects(){return <section className="mt-10 flex min-h-[430px] items-center justify-center rounded-[2rem] border border-dashed border-border bg-card/70 px-6 text-center"><div className="max-w-md"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-[1.4rem] bg-secondary text-primary"><FolderKanban className="h-7 w-7"/></div><h2 className="mt-6 text-2xl font-bold">Проектов пока нет</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Создайте первый проект, укажите задачу, бюджет и сроки. После публикации подрядчики смогут отправлять вам свои предложения.</p><Link href="/customer/projects/new" className="mt-6 inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-primary px-5 font-semibold text-primary-foreground"><Plus className="h-5 w-5"/>Создать первый проект</Link></div></section>}
function getCategoryName(value:{id:string|number;name:string}|Array<{id:string|number;name:string}>|null|undefined){return Array.isArray(value)?(value[0]?.name??"Категория не указана"):(value?.name??"Категория не указана")}
function ProjectStatusBadge({status}:{status:string}){const c=getProjectStatusConfig(status);return <span className={["inline-flex items-center rounded-full px-3 py-1.5 text-xs font-semibold",c.className].join(" ")}>{c.label}</span>}
function getProjectStatusConfig(status:string){switch(status){case"draft":return{label:"Черновик",className:"bg-muted text-muted-foreground"};case"submitted":return{label:"Отправлен",className:"bg-secondary text-secondary-foreground"};case"moderation":return{label:"На модерации",className:"bg-violet-50 text-violet-700"};case"needs_clarification":return{label:"Требует уточнения",className:"bg-orange-50 text-orange-700"};case"published":return{label:"Опубликован",className:"bg-emerald-50 text-emerald-700"};case"collecting_bids":return{label:"Сбор предложений",className:"bg-cyan-50 text-cyan-700"};case"contractor_selected":return{label:"Подрядчик выбран",className:"bg-indigo-50 text-indigo-700"};case"in_progress":return{label:"В работе",className:"bg-amber-50 text-amber-700"};case"completed":return{label:"Завершён",className:"bg-green-50 text-green-700"};case"cancelled":return{label:"Отменён",className:"bg-red-50 text-red-700"};case"disputed":return{label:"Спор",className:"bg-rose-50 text-rose-700"};default:return{label:status,className:"bg-muted text-muted-foreground"}}}
function InfoItem({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="min-w-0 rounded-2xl bg-secondary/45 p-4"><div className="flex items-center gap-2 text-primary">{icon}<p className="text-xs font-medium text-muted-foreground">{label}</p></div><p className="mt-2 break-words text-sm font-semibold leading-5">{value}</p></div>}
function formatBudget(min:number|string|null,max:number|string|null){const f=new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0});if(min!==null&&max!==null)return `${f.format(Number(min))} — ${f.format(Number(max))}`;if(min!==null)return `От ${f.format(Number(min))}`;if(max!==null)return `До ${f.format(Number(max))}`;return"Не указан"}
function formatDateTime(value:string|null){if(!value)return null;return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
