import { BadgeCheck, Boxes, CircleDollarSign, ClipboardList, PackageSearch, ShoppingCart, Truck } from "lucide-react";
import { redirect } from "next/navigation";

import { db } from "@/lib/db/pool";
import { requireActiveUser } from "@/lib/auth/require-active-user";
import { getMaterialProjectParticipant } from "@/lib/materials/get-material-project-participant";
import { addMaterialItem, createMaterialList, removeMaterialItem, requestMaterialTender, selectMaterialQuote } from "@/features/materials/actions/project-materials";

type Role="customer"|"contractor";
type ListRow={id:string;title:string;status:string;selected_quote_id:string|null;created_at:Date|string};
type ItemRow={id:string;product_id:string|null;description:string;quantity:string|number;unit:string};
type ProductRow={id:string;canonical_name:string;brand:string|null;model:string|null;unit:string};
type RequestRow={id:string;status:string;requested_at:Date|string;closes_at:Date|string|null};
type QuoteRow={id:string;supplier_id:string;public_name:string;status:string;goods_subtotal_minor:string|number;delivery_minor:string|number|null;missing_item_count:number;max_lead_time_days:number;valid_until:Date|string|null};

type Props={projectId:string;role:Role;query:Record<string,string|string[]|undefined>};
export async function ProjectMaterialsPage({projectId,role,query}:Props){
 const activeUser=await requireActiveUser();if(!activeUser.success)redirect("/login");if(activeUser.profile.role!==role)redirect("/dashboard");const ctx=await getMaterialProjectParticipant(projectId,activeUser.user.id,activeUser.profile.role);if(!ctx.success)redirect(`/${role}/work/${projectId}`);
 const listResult=await db.query<ListRow>(`SELECT id,title,status,selected_quote_id,created_at FROM public.project_material_lists WHERE project_id=$1::uuid ORDER BY created_at DESC LIMIT 1`,[projectId]);const list=listResult.rows[0]??null;
 const [itemsResult,productsResult,requestResult]=await Promise.all([
   list?db.query<ItemRow>(`SELECT id,product_id,description,quantity,unit FROM public.project_material_items WHERE list_id=$1::uuid ORDER BY sort_order,created_at`,[list.id]):Promise.resolve({rows:[]} as {rows:ItemRow[]}),
   db.query<ProductRow>(`SELECT id,canonical_name,brand,model,unit FROM public.material_products WHERE is_active=true ORDER BY canonical_name LIMIT 1000`),
   list?db.query<RequestRow>(`SELECT id,status,requested_at,closes_at FROM public.material_procurement_requests WHERE list_id=$1::uuid ORDER BY requested_at DESC LIMIT 1`,[list.id]):Promise.resolve({rows:[]} as {rows:RequestRow[]}),
 ]);
 const request=requestResult.rows[0]??null;
 const quotesResult=request?await db.query<QuoteRow>(`SELECT q.id,q.supplier_id,s.public_name,q.status,q.goods_subtotal_minor,q.delivery_minor,q.missing_item_count,q.max_lead_time_days,q.valid_until FROM public.material_procurement_quotes q JOIN public.material_suppliers s ON s.id=q.supplier_id WHERE q.request_id=$1::uuid ORDER BY q.missing_item_count ASC,(q.goods_subtotal_minor+COALESCE(q.delivery_minor,0)) ASC,s.public_name`,[request.id]):{rows:[] as QuoteRow[]};
 const notice=query.created?"Ведомость создана":query.item?"Позиция добавлена":query.removed?"Позиция удалена":query.tender?"Тендер сформирован по актуальным прайсам поставщиков":query.selected?"Поставщик выбран. На следующем этапе можно будет оформить заказ и доставку.":query.error?errorMessage(String(query.error)):null;
 const editable=ctx.project.status==="contractor_selected"||ctx.project.status==="in_progress";
 return <main className="app-container space-y-6 py-6 md:py-8">
  <section className="rounded-[2rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] md:p-8"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><ShoppingCart className="h-5 w-5"/></div><div><p className="text-sm font-semibold text-primary">Закупки объекта</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em]">Стройматериалы</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Сформируйте ведомость. StroySelect сравнит одинаковые товары у подключённых поставщиков, зафиксирует цену, наличие и срок, а неполные предложения отметит отдельно.</p></div></div></section>
  {notice&&<div className="rounded-2xl border border-border bg-card p-4 text-sm font-semibold">{notice}</div>}
  {!list?<section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center gap-2"><ClipboardList className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">Создать ведомость материалов</h2></div><p className="mt-2 text-sm text-muted-foreground">Например: «Система отопления», «Черновая электрика» или «Материалы для санузла».</p>{editable?<form action={createMaterialList} className="mt-5 flex flex-col gap-3 sm:flex-row"><input type="hidden" name="projectId" value={projectId}/><input name="title" required maxLength={240} placeholder="Название ведомости" className="min-h-11 flex-1 rounded-xl border border-border bg-background px-4 text-sm"/><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Создать ведомость</button></form>:<p className="mt-5 text-sm font-semibold text-muted-foreground">Проект завершён: создание новых закупок недоступно.</p>}</section>:<>
   <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-sm font-semibold text-primary">Ведомость</p><h2 className="mt-1 text-2xl font-bold">{list.title}</h2><p className="mt-2 text-xs text-muted-foreground">Статус: {listStatus(list.status)} · создана {date(list.created_at)}</p></div><span className="rounded-full bg-secondary px-3 py-1.5 text-xs font-bold text-primary">{itemsResult.rows.length} позиций</span></div>
    <div className="mt-5 divide-y divide-border">{itemsResult.rows.map(item=><div key={item.id} className="flex flex-col gap-3 py-4 first:pt-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.description}</p><p className="mt-1 text-sm text-muted-foreground">{number(item.quantity)} {item.unit}{item.product_id?" · сопоставлено с каталогом":" · требует сопоставления"}</p></div>{list.status==="draft"&&editable&&<form action={removeMaterialItem}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="listId" value={list.id}/><input type="hidden" name="itemId" value={item.id}/><button className="rounded-xl border border-border px-3 py-2 text-xs font-semibold text-muted-foreground">Удалить</button></form>}</div>)}{itemsResult.rows.length===0&&<p className="py-6 text-center text-sm text-muted-foreground">Добавьте первую позицию.</p>}</div>
   </section>
   {list.status==="draft"&&editable&&<section className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><div className="rounded-[1.75rem] border border-border bg-card p-6"><div className="flex items-center gap-2"><PackageSearch className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">Добавить материал</h2></div><form action={addMaterialItem} className="mt-5 grid gap-3 sm:grid-cols-2"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="listId" value={list.id}/><select name="productId" className="rounded-xl border border-border bg-background px-3 py-3 text-sm sm:col-span-2"><option value="">Нет в каталоге — добавить вручную</option>{productsResult.rows.map(p=><option key={p.id} value={p.id}>{p.canonical_name}{p.brand?` · ${p.brand}`:""}</option>)}</select><input name="description" placeholder="Описание, если товара нет в каталоге" maxLength={500} className="rounded-xl border border-border bg-background px-3 py-3 text-sm sm:col-span-2"/><input name="quantity" type="number" min="0.001" step="0.001" required placeholder="Количество" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="unit" defaultValue="шт" maxLength={40} placeholder="Ед. изм." className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground sm:col-span-2">Добавить в ведомость</button></form></div><div className="rounded-[1.75rem] border border-border bg-card p-6"><div className="flex items-center gap-2"><Boxes className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">Запустить сравнение</h2></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Тендер зафиксирует текущие цены и остатки всех активных поставщиков. После запуска состав ведомости уже не меняется.</p><form action={requestMaterialTender} className="mt-5"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="listId" value={list.id}/><button disabled={itemsResult.rows.length===0} className="min-h-11 w-full rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">Получить предложения поставщиков</button></form></div></section>}
   {(list.status==="requested"||list.status==="selected")&&<section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center gap-2"><CircleDollarSign className="h-5 w-5 text-primary"/><div><h2 className="text-xl font-bold">Сравнение поставщиков</h2><p className="mt-1 text-xs text-muted-foreground">Цена и наличие зафиксированы на момент запроса{request?` ${dateTime(request.requested_at)}`:""}. Доставка пока не включена.</p></div></div><div className="mt-5 grid gap-4 xl:grid-cols-2">{quotesResult.rows.map((quote,index)=>{const complete=quote.missing_item_count===0;const selected=list.selected_quote_id===quote.id;return <article key={quote.id} className={["rounded-2xl border p-5",selected?"border-primary bg-secondary/40":"border-border bg-background/60"].join(" ")}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold">{quote.public_name}</h3>{index===0&&complete&&<span className="rounded-full bg-primary px-2.5 py-1 text-[11px] font-bold text-primary-foreground">Лучшая полная цена</span>}{selected&&<BadgeCheck className="h-5 w-5 text-primary"/>}</div><p className="mt-2 text-xs text-muted-foreground">Покрытие: {Math.max(0,itemsResult.rows.length-quote.missing_item_count)} из {itemsResult.rows.length} позиций · срок до {quote.max_lead_time_days} дн.</p></div><p className="text-xl font-black">{money(quote.goods_subtotal_minor)}</p></div>{!complete&&<div className="mt-4 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">Не хватает позиций: {quote.missing_item_count}. Такое предложение нельзя выбрать победителем.</div>}<div className="mt-4 flex items-center justify-between gap-3 border-t border-border pt-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Truck className="h-4 w-4"/>Доставка будет рассчитана отдельно</div>{list.status==="requested"&&editable&&complete&&<form action={selectMaterialQuote}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="listId" value={list.id}/><input type="hidden" name="quoteId" value={quote.id}/><button className="rounded-xl bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground">Выбрать поставщика</button></form>}</div></article>})}{quotesResult.rows.length===0&&<p className="text-sm text-muted-foreground">Поставщики пока не дали сравнимых предложений.</p>}</div></section>}
   {list.status==="selected"&&<section className="rounded-[1.75rem] border border-primary/30 bg-secondary/40 p-6"><h2 className="text-xl font-bold">Поставщик выбран</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Следующий коммерческий блок превратит это предложение в заказ материалов, а модуль доставки рассчитает маршрут и стоимость до объекта.</p></section>}
  </>}
 </main>
}
function money(v:string|number){return new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(Number(v)/100)}function number(v:string|number){return Number(v).toLocaleString("ru-RU",{maximumFractionDigits:3})}function date(v:Date|string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium"}).format(new Date(v))}function dateTime(v:Date|string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}function listStatus(v:string){return v==="draft"?"Черновик":v==="requested"?"Сравнение поставщиков":v==="selected"?"Поставщик выбран":v==="ordered"?"Заказано":v==="completed"?"Завершено":v==="cancelled"?"Отменено":v}function errorMessage(code:string){const m:Record<string,string>={list:"Проверьте название ведомости.","active-list":"Сначала завершите текущую ведомость.",item:"Проверьте позицию и количество.",product:"Материал не найден в каталоге.","list-state":"Эту ведомость уже нельзя изменять.",empty:"Ведомость пуста.","no-suppliers":"Пока нет активных поставщиков для сравнения.",tender:"Не удалось сформировать тендер.",quote:"Не удалось выбрать это предложение.",status:"На текущем статусе проекта новая закупка недоступна."};return m[code]??"Операция не выполнена."}
