import Link from "next/link";
import { MapPin, Save, Truck } from "lucide-react";
import { notFound } from "next/navigation";
import { db } from "@/lib/db/pool";
import { saveMaterialSupplierLocation } from "@/features/admin/actions/manage-material-delivery";

type Supplier={id:string;public_name:string;contact_phone:string|null;contact_email:string|null};
type Location={id:string;name:string;address:string;region:string|null;city:string|null;latitude:string|number|null;longitude:string|number|null;phone:string|null;loading_notes:string|null;is_active:boolean};
type Props={params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
export default async function SupplierDeliveryPage({params,searchParams}:Props){const [{id},query]=await Promise.all([params,searchParams]);const [supplierResult,locationsResult]=await Promise.all([db.query<Supplier>(`SELECT id,public_name,contact_phone,contact_email FROM public.material_suppliers WHERE id=$1::uuid LIMIT 1`,[id]),db.query<Location>(`SELECT id,name,address,region,city,latitude,longitude,phone,loading_notes,is_active FROM public.material_supplier_locations WHERE supplier_id=$1::uuid ORDER BY is_active DESC,name`,[id])]);const supplier=supplierResult.rows[0];if(!supplier)notFound();return <div className="space-y-6"><section className="rounded-[2rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] md:p-8"><div className="flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Truck className="h-5 w-5"/></div><div><p className="text-sm font-semibold text-primary">Яндекс Доставка</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em]">Точки отгрузки · {supplier.public_name}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Для расчёта доставки обязательно нужны точный адрес и координаты склада. Координаты хранятся отдельно как широта и долгота; в API Яндекса StroySelect отправляет их в требуемом порядке долгота → широта.</p></div></div></section>{query.saved&&<div className="rounded-2xl border border-border bg-card p-4 text-sm font-semibold">Точка отгрузки сохранена.</div>}{query.error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">Проверьте адрес и координаты точки.</div>}<LocationForm supplierId={id} location={null} defaultPhone={supplier.contact_phone}/>{locationsResult.rows.map(location=><LocationForm key={location.id} supplierId={id} location={location} defaultPhone={supplier.contact_phone}/>)}<Link href="/admin/suppliers" className="inline-flex text-sm font-semibold text-primary">← К поставщикам</Link></div>}
function LocationForm({supplierId,location,defaultPhone}:{supplierId:string;location:Location|null;defaultPhone:string|null}){return <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">{location?location.name:"Новая точка отгрузки"}</h2></div><form action={saveMaterialSupplierLocation} className="mt-5 grid gap-3 md:grid-cols-2"><input type="hidden" name="supplierId" value={supplierId}/>{location&&<input type="hidden" name="locationId" value={location.id}/>}<input name="name" required maxLength={160} defaultValue={location?.name??""} placeholder="Название склада / магазина" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="phone" defaultValue={location?.phone??defaultPhone??""} placeholder="Телефон точки" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="address" required defaultValue={location?.address??""} placeholder="Полный адрес" className="rounded-xl border border-border bg-background px-3 py-3 text-sm md:col-span-2"/><input name="region" defaultValue={location?.region??""} placeholder="Регион" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="city" defaultValue={location?.city??""} placeholder="Город" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="latitude" required type="number" step="0.0000001" min="-90" max="90" defaultValue={location?.latitude===null||location?.latitude===undefined?"":String(location.latitude)} placeholder="Широта, например 42.9849" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="longitude" required type="number" step="0.0000001" min="-180" max="180" defaultValue={location?.longitude===null||location?.longitude===undefined?"":String(location.longitude)} placeholder="Долгота, например 47.5047" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><textarea name="loadingNotes" defaultValue={location?.loading_notes??""} placeholder="Как заехать, где погрузка, ограничения" className="min-h-24 rounded-xl border border-border bg-background px-3 py-3 text-sm md:col-span-2"/><label className="flex items-center gap-2 text-sm font-semibold"><input name="active" type="checkbox" defaultChecked={location?.is_active??true}/>Активная точка</label><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground"><Save className="h-4 w-4"/>Сохранить</button></form></section>}
