import { Building2, FileSpreadsheet, Percent } from "lucide-react";
import { db } from "@/lib/db/pool";
import { createMaterialSupplier, importSupplierCatalogCsv, updateMaterialSupplier } from "@/features/admin/actions/manage-material-marketplace";

type Supplier={id:string;public_name:string;legal_name:string|null;inn:string|null;status:string;commission_bps:number;integration_mode:string;contact_email:string|null;contact_phone:string|null;offer_count:string|number;last_import_at:Date|string|null};
type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};
export default async function AdminSuppliersPage({searchParams}:Props){const [result,query]=await Promise.all([db.query<Supplier>(`SELECT s.id,s.public_name,s.legal_name,s.inn,s.status,s.commission_bps,s.integration_mode,s.contact_email,s.contact_phone,COUNT(DISTINCT o.id) AS offer_count,MAX(ci.created_at) AS last_import_at FROM public.material_suppliers s LEFT JOIN public.material_supplier_offers o ON o.supplier_id=s.id AND o.is_active=true LEFT JOIN public.material_catalog_imports ci ON ci.supplier_id=s.id GROUP BY s.id ORDER BY s.public_name`),searchParams]);const message=query.created?"Поставщик добавлен":query.saved?"Настройки поставщика сохранены":query.imported?"CSV-каталог обработан":query.error?"Операция не выполнена":null;return <div className="space-y-6">
<section className="rounded-[2rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] md:p-8"><p className="text-sm font-semibold text-primary">Marketplace стройматериалов</p><h1 className="mt-2 text-3xl font-black tracking-[-0.04em]">Поставщики</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Подключайте магазины и базы, задавайте комиссию StroySelect и способ синхронизации. Сейчас доступен ручной ввод и CSV; модель данных уже готова для API, XML/YML, 1С и МойСклад.</p></section>
{message&&<div className="rounded-2xl border border-border bg-card p-4 text-sm font-semibold">{message}</div>}
<section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">Новый поставщик</h2></div><form action={createMaterialSupplier} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input name="publicName" required placeholder="Название для покупателей" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="legalName" placeholder="Юридическое название" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="inn" placeholder="ИНН" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="email" type="email" placeholder="Email" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><input name="phone" placeholder="Телефон" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"/><select name="integrationMode" defaultValue="manual" className="rounded-xl border border-border bg-background px-3 py-3 text-sm"><option value="manual">Ручной</option><option value="csv">CSV</option><option value="api">API</option><option value="xml">XML</option><option value="yml">YML</option><option value="1c">1С</option><option value="moysklad">МойСклад</option></select><label className="flex items-center gap-2 rounded-xl border border-border px-3 text-sm"><Percent className="h-4 w-4 text-primary"/><input name="commissionPercent" type="number" min="0" max="100" step="0.1" defaultValue="5" className="min-w-0 flex-1 bg-transparent py-3 outline-none"/>%</label><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Добавить</button></form></section>
<section className="space-y-4">{result.rows.map(s=><article key={s.id} className="rounded-[1.5rem] border border-border bg-card p-5 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><h3 className="text-lg font-bold">{s.public_name}</h3><p className="mt-1 text-xs text-muted-foreground">{s.legal_name??"Юр. название не указано"}{s.inn?` · ИНН ${s.inn}`:""}</p><p className="mt-2 text-sm text-muted-foreground">Активных позиций: {Number(s.offer_count)}{s.last_import_at?` · последний импорт ${formatDate(s.last_import_at)}`:""}</p></div><form action={updateMaterialSupplier} className="grid gap-2 sm:grid-cols-4"><input type="hidden" name="supplierId" value={s.id}/><select name="status" defaultValue={s.status} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="pending">Ожидает</option><option value="active">Активен</option><option value="suspended">Приостановлен</option><option value="archived">Архив</option></select><select name="integrationMode" defaultValue={s.integration_mode} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="manual">Ручной</option><option value="csv">CSV</option><option value="api">API</option><option value="xml">XML</option><option value="yml">YML</option><option value="1c">1С</option><option value="moysklad">МойСклад</option></select><input name="commissionPercent" type="number" min="0" max="100" step="0.1" defaultValue={(s.commission_bps/100).toFixed(1)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"/><button className="rounded-xl border border-primary px-4 py-2 text-sm font-semibold text-primary">Сохранить</button></form></div><div className="mt-5 border-t border-border pt-5"><form action={importSupplierCatalogCsv} className="flex flex-col gap-3 md:flex-row md:items-center"><input type="hidden" name="supplierId" value={s.id}/><FileSpreadsheet className="h-5 w-5 text-primary"/><input type="file" name="catalog" accept=".csv,text/csv" required className="min-w-0 flex-1 text-sm"/><button className="rounded-xl bg-secondary px-4 py-2.5 text-sm font-semibold text-primary">Импортировать CSV</button></form><p className="mt-2 text-xs text-muted-foreground">Колонки: supplier_sku, canonical_name, unit, price, stock; дополнительно brand, model, category, raw_name, lead_time_days. Цена указывается в рублях.</p></div></article>)}{result.rows.length===0&&<p className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">Поставщиков пока нет.</p>}</section>
</div>}
function formatDate(v:Date|string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
