import { BadgeCheck, CircleDollarSign, Megaphone, ShieldCheck } from "lucide-react";

import { db } from "@/lib/db/pool";
import { activateScheduledAd, completeAdOrder, moderateAdOrder, reconcileAdLevyQuarter, recordAdEridAndSchedule, setAdAdvertiserStatus, updateAdPlacement } from "@/features/admin/actions/manage-advertising";

type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};
type Placement={id:string;code:string;name:string;description:string|null;unit_price_minor:string|number;currency:string;min_days:number;max_days:number;is_active:boolean;requires_erid:boolean};
type Advertiser={id:string;display_name:string;legal_name:string;inn:string;ogrn:string|null;website_url:string|null;status:string;verification_notes:string|null;created_at:Date|string};
type Order={id:string;status:string;amount_minor:string|number;currency:string;duration_days_snapshot:number;placement_name_snapshot:string;advertiser_name_snapshot:string;advertiser_inn_snapshot:string;title_snapshot:string;body_snapshot:string;destination_url_snapshot:string;created_at:Date|string;scheduled_from:Date|string|null;scheduled_to:Date|string|null;rejection_reason:string|null;creative_status:string;erid:string|null;ord_provider:string|null;ord_creative_id:string|null;impressions:string|number;clicks:string|number};
type Levy={quarter_start:Date|string;revenue_minor:string|number;rate_bps:number;estimated_levy_minor:string|number;assessed_levy_minor:string|number|null;status:string;notes:string|null;paid_at:Date|string|null};

export default async function AdminAdsPage({searchParams}:Props){
  const query=await searchParams;
  const [placements,advertisers,orders,levies]=await Promise.all([
    db.query<Placement>(`SELECT id,code,name,description,unit_price_minor,currency,min_days,max_days,is_active,requires_erid FROM public.ad_placements ORDER BY sort_order,name`),
    db.query<Advertiser>(`SELECT id,display_name,legal_name,inn,ogrn,website_url,status,verification_notes,created_at FROM public.ad_advertisers ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'rejected' THEN 1 ELSE 2 END,created_at DESC`),
    db.query<Order>(`
      SELECT o.id,o.status,o.amount_minor,o.currency,o.duration_days_snapshot,o.placement_name_snapshot,o.advertiser_name_snapshot,o.advertiser_inn_snapshot,o.title_snapshot,o.body_snapshot,o.destination_url_snapshot,o.created_at,o.scheduled_from,o.scheduled_to,o.rejection_reason,
        cr.status AS creative_status,cr.erid,cr.ord_provider,cr.ord_creative_id,
        COUNT(e.id) FILTER (WHERE e.event_type='impression') AS impressions,
        COUNT(e.id) FILTER (WHERE e.event_type='click') AS clicks
      FROM public.ad_orders o JOIN public.ad_creatives cr ON cr.id=o.creative_id LEFT JOIN public.ad_events e ON e.order_id=o.id
      GROUP BY o.id,cr.status,cr.erid,cr.ord_provider,cr.ord_creative_id
      ORDER BY CASE o.status WHEN 'moderation' THEN 0 WHEN 'approved' THEN 1 WHEN 'paid' THEN 2 WHEN 'scheduled' THEN 3 WHEN 'active' THEN 4 ELSE 5 END,o.created_at DESC
    `),
    db.query<Levy>(`SELECT quarter_start,revenue_minor,rate_bps,estimated_levy_minor,assessed_levy_minor,status,notes,paid_at FROM public.ad_levy_quarter_estimates ORDER BY quarter_start DESC`),
  ]);
  const message=query.saved?"Изменения сохранены.":query.moderated?"Решение модерации сохранено.":query.published?"ERID и расписание сохранены; статус показа обновлён.":query.completed?"Рекламное размещение завершено.":query.error?"Операция не выполнена: проверьте состояние заказа и введённые данные.":null;

  return <div className="space-y-7">
    <section className="rounded-[2rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] md:p-8"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Megaphone className="h-5 w-5"/></div><div><p className="text-sm font-semibold text-primary">Монетизация</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em]">Реклама · модерация · ЕРИР</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Оплата и публикация разделены. Активировать рекламный заказ можно только после проверки рекламодателя, модерации креатива и фиксации ERID/ОРД.</p></div></div></section>
    {message&&<div className="rounded-2xl border border-border bg-card p-4 text-sm font-semibold">{message}</div>}

    <section className="grid gap-4 md:grid-cols-3"><Info icon={<CircleDollarSign className="h-5 w-5"/>} title="3% — внутренний резерв" text="Система считает ориентировочный резерв 3% от подтверждённой рекламной выручки. Итоговое обязательство сверяется с данными Роскомнадзора/ЕРИР, а не определяется этим экраном."/><Info icon={<ShieldCheck className="h-5 w-5"/>} title="Не auto-publish" text="YooKassa переводит заказ только в статус «Оплачен». Модерация и ERID остаются отдельными обязательными шагами."/><Info icon={<BadgeCheck className="h-5 w-5"/>} title="Органика отдельно" text="Спонсорские блоки рендерятся отдельным компонентом и не изменяют matching score, рейтинг подрядчиков или органическую сортировку."/></section>

    <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><h2 className="text-2xl font-bold">Рекламные места и тарифы</h2><div className="mt-5 grid gap-4 xl:grid-cols-2">{placements.rows.map(p=><form key={p.id} action={updateAdPlacement} className="rounded-2xl border border-border bg-background p-5"><input type="hidden" name="placementId" value={p.id}/><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-primary">{p.code}</p><h3 className="mt-1 font-bold">{p.name}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{p.description}</p></div><span className="text-sm font-black">{money(p.unit_price_minor,p.currency)}/день</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="Цена, ₽/день"><input name="priceRub" type="number" min="0" step="1" defaultValue={(Number(p.unit_price_minor)/100).toFixed(0)} className="stroy-input mt-1"/></Field><Field label="Мин. дней"><input name="minDays" type="number" min="1" max="365" defaultValue={p.min_days} className="stroy-input mt-1"/></Field><Field label="Макс. дней"><input name="maxDays" type="number" min="1" max="365" defaultValue={p.max_days} className="stroy-input mt-1"/></Field></div><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input name="active" type="checkbox" defaultChecked={p.is_active}/>Активно для новых заказов</label><button className="mt-4 rounded-xl border border-primary px-4 py-2.5 text-sm font-semibold text-primary">Сохранить тариф</button></form>)}</div></section>

    <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><h2 className="text-2xl font-bold">Рекламодатели</h2><div className="mt-5 space-y-3">{advertisers.rows.map(a=><form key={a.id} action={setAdAdvertiserStatus} className="rounded-2xl border border-border bg-background p-5"><input type="hidden" name="advertiserId" value={a.id}/><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{a.display_name}</h3><Status value={a.status}/></div><p className="mt-1 text-xs text-muted-foreground">{a.legal_name} · ИНН {a.inn}{a.ogrn?` · ОГРН ${a.ogrn}`:""}</p>{a.website_url&&<a href={a.website_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex break-all text-xs font-semibold text-primary">{a.website_url}</a>}</div><div className="grid gap-2 sm:grid-cols-[180px_1fr_auto]"><label className="text-xs font-semibold text-muted-foreground">Статус<select name="status" defaultValue={a.status} className="stroy-input mt-1"><option value="pending">Ожидает</option><option value="verified">Проверен</option><option value="rejected">Отклонён</option><option value="suspended">Приостановлен</option></select></label><label className="text-xs font-semibold text-muted-foreground">Комментарий<input name="notes" defaultValue={a.verification_notes??""} className="stroy-input mt-1"/></label><button className="self-end rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Сохранить</button></div></div></form>)}{advertisers.rows.length===0&&<p className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Рекламодателей пока нет.</p>}</div></section>

    <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><h2 className="text-2xl font-bold">Заказы и модерация</h2><div className="mt-5 space-y-4">{orders.rows.map(o=><article key={o.id} className="rounded-2xl border border-border bg-background p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold text-primary">{o.placement_name_snapshot}</p><Status value={o.status}/></div><h3 className="mt-2 text-lg font-bold">{o.title_snapshot}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{o.body_snapshot}</p><p className="mt-2 text-xs text-muted-foreground">Рекламодатель: {o.advertiser_name_snapshot} · ИНН {o.advertiser_inn_snapshot}</p><a href={o.destination_url_snapshot} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex break-all text-xs font-semibold text-primary">{o.destination_url_snapshot}</a></div><div className="grid shrink-0 grid-cols-3 gap-2 text-center"><Metric label="Сумма" value={money(o.amount_minor,o.currency)}/><Metric label="Показы" value={String(o.impressions)}/><Metric label="Клики" value={String(o.clicks)}/></div></div>
      {o.status==="moderation"&&<form action={moderateAdOrder} className="mt-4 rounded-xl border border-border p-4"><input type="hidden" name="orderId" value={o.id}/><label className="block text-xs font-semibold text-muted-foreground">Комментарий модератора<textarea name="notes" rows={2} className="stroy-input mt-1 resize-y" placeholder="Обязателен при отклонении"/></label><div className="mt-3 flex gap-2"><button name="decision" value="approve" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Одобрить</button><button name="decision" value="reject" className="rounded-xl border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700">Отклонить</button></div></form>}
      {o.status==="approved"&&<form action={recordAdEridAndSchedule} className="mt-4 rounded-xl border border-border p-4"><input type="hidden" name="orderId" value={o.id}/><div className="grid gap-3 md:grid-cols-2"><Field label="ERID"><input name="erid" required maxLength={160} className="stroy-input mt-1" placeholder="Идентификатор рекламы"/></Field><Field label="Оператор рекламных данных"><input name="ordProvider" required maxLength={100} className="stroy-input mt-1" placeholder="Название ОРД"/></Field><Field label="ID креатива у ОРД"><input name="ordCreativeId" className="stroy-input mt-1"/></Field><label className="flex items-center gap-2 self-end rounded-xl border border-border p-3 text-sm font-semibold"><input name="startNow" type="checkbox"/>Запустить сейчас на оплаченный срок</label><Field label="Начало, МСК"><input name="scheduledFrom" type="datetime-local" className="stroy-input mt-1"/></Field><Field label="Окончание, МСК"><input name="scheduledTo" type="datetime-local" className="stroy-input mt-1"/></Field></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Если отмечено «Запустить сейчас», ручные даты игнорируются. Иначе период не может превышать оплаченные {o.duration_days_snapshot} дней.</p><button className="mt-3 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Зафиксировать ERID и расписание</button></form>}
      {o.erid&&<p className="mt-3 break-all text-xs text-muted-foreground">erid: {o.erid} · ОРД: {o.ord_provider??"—"}{o.ord_creative_id?` · ID ${o.ord_creative_id}`:""}</p>}
      {o.scheduled_from&&<p className="mt-2 text-xs text-muted-foreground">Показ: {date(o.scheduled_from)} — {o.scheduled_to?date(o.scheduled_to):"—"}</p>}
      {o.rejection_reason&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">Причина: {o.rejection_reason}</p>}
      {o.status==="scheduled"&&<form action={activateScheduledAd} className="mt-3 inline-block"><input type="hidden" name="orderId" value={o.id}/><button className="rounded-xl border border-primary px-4 py-2.5 text-sm font-semibold text-primary">Активировать, если срок начался</button></form>}
      {["scheduled","active"].includes(o.status)&&<form action={completeAdOrder} className="ml-2 mt-3 inline-block"><input type="hidden" name="orderId" value={o.id}/><button className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold">Завершить, если срок истёк</button></form>}
    </article>)}{orders.rows.length===0&&<p className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Рекламных заказов пока нет.</p>}</div></section>

    <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><h2 className="text-2xl font-bold">Резерв обязательных отчислений</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Это управленческий расчёт StroySelect. Закон устанавливает 3% базу, но окончательная сумма должна сверяться с расчётом и данными Роскомнадзора/ЕРИР по действующим правилам.</p><div className="mt-5 space-y-3">{levies.rows.map(l=><form key={String(l.quarter_start)} action={reconcileAdLevyQuarter} className="grid gap-3 rounded-2xl border border-border bg-background p-5 lg:grid-cols-[1fr_1fr_1fr_1fr_2fr_auto]"><input type="hidden" name="quarterStart" value={isoDate(l.quarter_start)}/><Metric label="Квартал" value={isoDate(l.quarter_start)}/><Metric label="Выручка" value={money(l.revenue_minor,"RUB")}/><Metric label="Оценка 3%" value={money(l.estimated_levy_minor,"RUB")}/><label className="text-xs font-semibold text-muted-foreground">Начислено РКН, ₽<input name="assessedRub" type="number" min="0" step="0.01" defaultValue={l.assessed_levy_minor===null?"":(Number(l.assessed_levy_minor)/100).toFixed(2)} className="stroy-input mt-1" required/></label><label className="text-xs font-semibold text-muted-foreground">Сверка<select name="status" defaultValue={l.status==="paid"?"paid":"reconciled"} className="stroy-input mt-1"><option value="reconciled">Сверено</option><option value="paid">Оплачено</option></select><input name="notes" defaultValue={l.notes??""} placeholder="Комментарий" className="stroy-input mt-2"/></label><button className="self-end rounded-xl border border-primary px-4 py-2.5 text-sm font-semibold text-primary">Сохранить</button></form>)}{levies.rows.length===0&&<p className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Подтверждённой рекламной выручки пока нет.</p>}</div></section>
  </div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-semibold text-muted-foreground">{label}{children}</label>}
function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-[1.5rem] border border-border bg-card p-5 shadow-[var(--shadow-soft)]"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-primary">{icon}</div><h2 className="mt-4 font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words font-bold">{value}</p></div>}
function Status({value}:{value:string}){const [label,cls]=status(value);return <span className={`inline-flex shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${cls}`}>{label}</span>}
function status(value:string):[string,string]{switch(value){case"verified":return["Проверен","bg-emerald-50 text-emerald-700"];case"pending":return["Ожидает","bg-amber-50 text-amber-800"];case"paid":return["Оплачен","bg-blue-50 text-blue-800"];case"moderation":return["Модерация","bg-violet-50 text-violet-800"];case"approved":return["Одобрен","bg-emerald-50 text-emerald-800"];case"rejected":return["Отклонён","bg-red-50 text-red-800"];case"scheduled":return["Запланирован","bg-sky-50 text-sky-800"];case"active":return["Активен","bg-emerald-50 text-emerald-800"];case"completed":return["Завершён","bg-secondary text-foreground"];case"awaiting_payment":return["Ожидает оплату","bg-amber-50 text-amber-800"];case"suspended":return["Приостановлен","bg-orange-50 text-orange-800"];default:return[value,"bg-secondary text-foreground"]}}
function money(value:string|number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value)/100)}
function date(value:Date|string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Moscow"}).format(new Date(value))}
function isoDate(value:Date|string){return new Date(value).toISOString().slice(0,10)}
