import { CreditCard, ShieldCheck, UsersRound } from "lucide-react";

import { db } from "@/lib/db/pool";
import { grantContractorSubscription, updateSubscriptionPlan } from "@/features/admin/actions/manage-contractor-subscriptions";

type Plan={id:string;code:string;name:string;duration_months:number;price_minor:string|number;currency:string;is_active:boolean};
type Subscription={contractor_id:string;public_name:string;status:string;current_period_end:Date|string;plan_name:string|null};
type Company={id:string;public_name:string;verification_status:string};

type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};

export default async function AdminSubscriptionsPage({searchParams}:Props){
  const query=await searchParams;
  const [plansResult,subscriptionsResult,companiesResult]=await Promise.all([
    db.query<Plan>(`SELECT id,code,name,duration_months,price_minor,currency,is_active FROM public.contractor_subscription_plans ORDER BY sort_order, duration_months`),
    db.query<Subscription>(`SELECT cs.contractor_id,cc.public_name,cs.status,cs.current_period_end,sp.name AS plan_name FROM public.contractor_subscriptions cs JOIN public.contractor_companies cc ON cc.id=cs.contractor_id LEFT JOIN public.contractor_subscription_plans sp ON sp.id=cs.plan_id ORDER BY cs.current_period_end ASC LIMIT 200`),
    db.query<Company>(`SELECT id,public_name,verification_status::text AS verification_status FROM public.contractor_companies ORDER BY public_name ASC LIMIT 500`),
  ]);
  const message=query.saved?"Тариф обновлён":query.granted?"Подписка выдана":query.error?"Операция не выполнена":null;
  return <div className="space-y-6">
    <section className="rounded-[2rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] md:p-8"><div className="flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><CreditCard className="h-5 w-5"/></div><div><p className="text-sm font-semibold text-primary">Монетизация подрядчиков</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em]">Подписки и тарифы</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Цена и доступность тарифов меняются из админки без deploy. Оплаченный период фиксируется в истории платежа и не меняется при последующем изменении цены.</p></div></div></section>
    {message&&<div className="rounded-2xl border border-border bg-card p-4 text-sm font-semibold">{message}</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plansResult.rows.map(plan=><form action={updateSubscriptionPlan} key={plan.id} className="rounded-[1.5rem] border border-border bg-card p-5 shadow-[var(--shadow-soft)]"><input type="hidden" name="planId" value={plan.id}/><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{plan.duration_months} мес.</p><label className="mt-4 block text-xs font-semibold text-muted-foreground">Название<input name="name" defaultValue={plan.name} required className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm text-foreground"/></label><label className="mt-3 block text-xs font-semibold text-muted-foreground">Цена, ₽<input name="priceRub" type="number" min="0" step="1" defaultValue={Math.round(Number(plan.price_minor)/100)} required className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm text-foreground"/></label><label className="mt-4 flex items-center gap-2 text-sm"><input name="isActive" type="checkbox" defaultChecked={plan.is_active}/>Тариф доступен</label><button className="mt-5 min-h-10 w-full rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Сохранить</button></form>)}</section>
    <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">Выдать или продлить подписку вручную</h2></div><form action={grantContractorSubscription} className="mt-5 grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,280px)_auto]"><select name="contractorId" required className="rounded-xl border border-border bg-background px-3 py-3 text-sm"><option value="">Выберите подрядчика</option>{companiesResult.rows.map(c=><option key={c.id} value={c.id}>{c.public_name} · {c.verification_status}</option>)}</select><select name="planId" required className="rounded-xl border border-border bg-background px-3 py-3 text-sm"><option value="">Выберите период</option>{plansResult.rows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Выдать</button></form></section>
    <section className="rounded-[1.75rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-primary"/><h2 className="text-xl font-bold">Текущие подписки</h2></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="px-3 py-3">Подрядчик</th><th className="px-3 py-3">Тариф</th><th className="px-3 py-3">Статус</th><th className="px-3 py-3">До</th></tr></thead><tbody>{subscriptionsResult.rows.map(s=><tr key={s.contractor_id} className="border-b border-border/70 last:border-0"><td className="px-3 py-4 font-semibold">{s.public_name}</td><td className="px-3 py-4">{s.plan_name??"—"}</td><td className="px-3 py-4">{statusLabel(s.status)}</td><td className="px-3 py-4">{formatDate(s.current_period_end)}</td></tr>)}</tbody></table>{subscriptionsResult.rows.length===0&&<p className="py-8 text-center text-sm text-muted-foreground">Активированных подписок пока нет.</p>}</div></section>
  </div>;
}
function formatDate(v:Date|string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
function statusLabel(v:string){return v==="active"?"Активна":v==="grace_period"?"Льготный период":v==="expired"?"Истекла":v==="cancelled"?"Отменена":v}
