import Link from "next/link";
import { AlertTriangle, CheckCircle2, CircleDot, Clock3, Plus } from "lucide-react";

import { createProjectIssue, updateProjectIssueStatus } from "@/features/workspace/actions/project-issues";

type Data = Awaited<ReturnType<typeof import("@/features/workspace/queries/get-project-issues").getProjectIssues>>;

export function ProjectIssuesBoard({ data, backHref }: { data: Data; backHref: string }) {
  const openCount=data.issues.filter(i=>i.status!=="resolved"&&i.status!=="cancelled").length;
  return <main className="min-h-screen bg-background"><div className="app-container py-8 md:py-12">
    <Link href={backHref} className="text-sm font-semibold text-muted-foreground hover:text-primary">← Вернуться в рабочее пространство</Link>
    <section className="mt-5 rounded-[2rem] border border-border bg-card p-6 shadow-[var(--shadow-soft)] md:p-8"><p className="text-sm font-semibold text-primary">Punch list & Issues</p><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] md:text-5xl">Замечания по работам</h1><p className="mt-3 text-sm text-muted-foreground">{data.project.title}. Открыто: {openCount}. Каждое замечание можно привязать к этапу, назначить приоритет и довести до решения.</p></section>

    <section className="mt-6 rounded-[1.75rem] border border-border bg-card p-5 md:p-6"><h2 className="text-xl font-black">Новое замечание</h2><form action={createProjectIssue} className="mt-4 grid gap-3 lg:grid-cols-2"><input type="hidden" name="projectId" value={data.project.id}/><input name="title" required minLength={3} maxLength={240} placeholder="Кратко опишите проблему" className="stroy-input"/><select name="stageId" className="stroy-input"><option value="">Без привязки к этапу</option>{data.stages.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><textarea name="description" maxLength={3000} placeholder="Что нужно исправить или проверить" className="stroy-textarea min-h-28 lg:col-span-2"/><select name="priority" defaultValue="normal" className="stroy-input"><option value="low">Низкий приоритет</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критический</option></select><input name="dueAt" type="date" className="stroy-input"/><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground lg:col-span-2"><Plus className="h-4 w-4"/>Создать замечание</button></form></section>

    <div className="mt-6 space-y-4">{data.issues.length===0?<div className="rounded-[1.5rem] border border-dashed border-border bg-card p-10 text-center text-sm text-muted-foreground">Замечаний пока нет.</div>:data.issues.map(issue=><article key={issue.id} className="rounded-[1.5rem] border border-border bg-card p-5 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2"><IssueStatus status={issue.status}/><Priority priority={issue.priority}/>{issue.stageTitle&&<span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-primary">{issue.stageTitle}</span>}</div><h2 className="mt-3 text-lg font-black text-foreground">{issue.title}</h2>{issue.description&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{issue.description}</p>}<p className="mt-3 text-xs text-muted-foreground">Создал: {issue.creatorName}{issue.assigneeName?` · Ответственный: ${issue.assigneeName}`:""}{issue.dueAt?` · Срок: ${formatDate(issue.dueAt)}`:""}</p></div><p className="shrink-0 text-xs text-muted-foreground">{formatDateTime(issue.createdAt)}</p></div>{issue.status!=="resolved"&&issue.status!=="cancelled"&&<form action={updateProjectIssueStatus} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="projectId" value={data.project.id}/><input type="hidden" name="issueId" value={issue.id}/>{issue.status==="open"&&<button name="status" value="in_progress" className="rounded-xl border border-border px-3 py-2 text-xs font-semibold">Взять в работу</button>}<button name="status" value="resolved" className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Отметить решённым</button><button name="status" value="cancelled" className="rounded-xl border border-border px-3 py-2 text-xs font-semibold text-muted-foreground">Отменить</button></form>}</article>)}</div>
  </div></main>;
}
function IssueStatus({status}:{status:string}){const item=status==="resolved"?{label:"Решено",icon:<CheckCircle2 className="h-3 w-3"/>,cls:"bg-emerald-50 text-emerald-700"}:status==="in_progress"?{label:"В работе",icon:<Clock3 className="h-3 w-3"/>,cls:"bg-amber-50 text-amber-700"}:status==="cancelled"?{label:"Отменено",icon:<CircleDot className="h-3 w-3"/>,cls:"bg-secondary text-muted-foreground"}:{label:"Открыто",icon:<CircleDot className="h-3 w-3"/>,cls:"bg-blue-50 text-blue-700"};return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-bold ${item.cls}`}>{item.icon}{item.label}</span>}
function Priority({priority}:{priority:string}){const label=priority==="critical"?"Критический":priority==="high"?"Высокий":priority==="low"?"Низкий":"Обычный";const cls=priority==="critical"?"bg-red-50 text-red-700":priority==="high"?"bg-orange-50 text-orange-700":"bg-secondary text-muted-foreground";return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-bold ${cls}`}>{(priority==="critical"||priority==="high")&&<AlertTriangle className="h-3 w-3"/>}{label}</span>}
function formatDate(v:string){const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium"}).format(d)}
function formatDateTime(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(d)}
