"use client";

import Link from "next/link";
import { useActionState, useState, useTransition } from "react";
import { Banknote,CheckCircle2,CircleDollarSign,CreditCard,FilePenLine,Receipt,ShieldAlert,XCircle } from "lucide-react";

import { StagePaymentButton } from "@/features/payments/components/stage-payment-button";
import { cancelChangeOrder,createChangeOrder,decideChangeOrder,recordProjectPayment } from "@/features/workspace/actions/change-orders";
import { cancelProjectPaymentConfirmation,confirmProjectPayment,disputeProjectPayment } from "@/features/workspace/actions/payment-confirmations";

type Intent={id:string;amount:number;status:string;provider:string;providerStatus:string|null;confirmationUrl:string|null;fundedAt:string|null;releaseReadyAt:string|null;paidAt:string|null;refundedAt:string|null;failureReason:string|null};
type Stage={id:string;title:string;status:string;sortOrder:number;progressWeight:number;stagePrice:number;paymentDuePercent:number|null;paymentDueAmount:number|null;plannedAmount:number;paidAmount:number;remainingAmount:number;paymentProgress:number;paymentIntent:Intent|null};
type Payment={id:string;stageId:string|null;amount:number;paidAt:string;note:string|null;confirmationStatus:string;customerConfirmedAt:string|null;contractorConfirmedAt:string|null;disputedAt:string|null;disputeReason:string|null;cancellationReason:string|null;currentUserConfirmed:boolean};
type Change={id:string;requestedByCurrentUser:boolean;title:string;reason:string;scopeChange:string;amountDelta:number;durationDeltaDays:number;status:string;decisionComment:string|null;createdAt:string};
type Data={role:"customer"|"contractor";paymentsEnabled:boolean;project:{id:string;title:string;status:string;originalContract:number;approvedDelta:number;currentContract:number;paidTotal:number;remaining:number;originalDurationDays:number;currentDurationDays:number};stages:Stage[];changes:Change[];payments:Payment[];paymentIntents:Intent[]};
type Result={success:boolean;message:string}|null;
type OperationKeys={changeOrder:string;payment:string};

export function ProjectBudgetControlV2({data,backHref,operationKeys}:{data:Data;backHref:string;operationKeys:OperationKeys}){
 const [changeKey,setChangeKey]=useState(operationKeys.changeOrder);
 const [paymentKey,setPaymentKey]=useState(operationKeys.payment);
 const [changeState,changeAction,changePending]=useActionState<Result,FormData>(async(_,form)=>{const result=await createChangeOrder(form);if(result.success)setChangeKey(crypto.randomUUID());return result},null);
 const [paymentState,paymentAction,paymentPending]=useActionState<Result,FormData>(async(_,form)=>{const result=await recordProjectPayment(form);if(result.success)setPaymentKey(crypto.randomUUID());return result},null);
 const [decisionState,decisionAction,decisionPending]=useActionState<Result,FormData>(async(_,form)=>decideChangeOrder(form),null);
 const [cancelState,cancelAction]=useActionState<Result,FormData>(async(_,form)=>cancelChangeOrder(form),null);

 return <main className="min-h-screen bg-background"><div className="app-container py-8 md:py-12">
  <Link href={backHref} className="text-sm font-semibold text-muted-foreground hover:text-primary">← Вернуться в рабочее пространство</Link>
  <section className="mt-5 rounded-[2rem] border border-border bg-card p-6 md:p-8">
   <p className="text-sm font-semibold text-primary">Контроль этапов и бюджета</p>
   <h1 className="mt-2 text-3xl font-black tracking-[-0.04em] md:text-5xl">Бюджет и платежи</h1>
   <p className="mt-3 max-w-3xl break-words text-sm text-muted-foreground">{data.project.title}. {data.paymentsEnabled?"Оплата проводится по этапам через ЮKassa. Деньги становятся доступными подрядчику только после явной приёмки этапа заказчиком.":"Онлайн-платежи пока отключены. Для тестового/переходного режима доступен ручной учёт только уже принятых этапов."}</p>
  </section>

  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
   <Metric icon={<Banknote className="h-5 w-5"/>} label="Стоимость по договору" value={money(data.project.originalContract)}/>
   <Metric icon={<FilePenLine className="h-5 w-5"/>} label="Согласованные изменения" value={signedMoney(data.project.approvedDelta)}/>
   <Metric icon={<CircleDollarSign className="h-5 w-5"/>} label="Текущая стоимость" value={money(data.project.currentContract)}/>
   <Metric icon={<Receipt className="h-5 w-5"/>} label="Заказчику осталось внести" value={money(data.project.remaining)}/>
  </section>

  <section className="mt-6 rounded-[1.75rem] border border-border bg-card p-5 md:p-6">
   <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-black">Расчёты по этапам</h2><p className="mt-1 text-sm text-muted-foreground">Каждый этап имеет самостоятельный статус денег и приёмки.</p></div>{data.paymentsEnabled&&<span className="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-800"><CreditCard className="h-4 w-4"/>ЮKassa включена</span>}</div>
   <div className="mt-5 space-y-4">{data.stages.length===0?<p className="text-sm text-muted-foreground">Этапы ещё не сформированы.</p>:data.stages.map(stage=><StagePaymentCard key={stage.id} stage={stage} projectId={data.project.id} role={data.role} paymentsEnabled={data.paymentsEnabled}/>)}</div>
  </section>

  <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-6">
   <section className="rounded-[1.75rem] border border-border bg-card p-5 md:p-6"><h2 className="text-xl font-black">Изменения к договору</h2><div className="mt-5 space-y-4">{data.changes.length===0?<p className="text-sm text-muted-foreground">Согласованных или ожидающих изменений нет.</p>:data.changes.map(change=><article key={change.id} className="rounded-xl border border-border p-4"><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><Status status={change.status}/><h3 className="mt-2 break-words font-bold">{change.title}</h3><p className="text-xs text-muted-foreground">{formatDateTime(change.createdAt)}</p></div><strong className="shrink-0">{signedMoney(change.amountDelta)}</strong></div><p className="mt-3 break-words text-sm"><b>Причина:</b> {change.reason}</p><p className="mt-2 break-words text-sm"><b>Что меняется:</b> {change.scopeChange}</p>{change.durationDeltaDays!==0&&<p className="mt-2 text-sm"><b>Изменение срока:</b> {change.durationDeltaDays>0?"+":""}{change.durationDeltaDays} дн.</p>}{change.decisionComment&&<p className="mt-2 break-words text-sm">Комментарий: {change.decisionComment}</p>}{change.status==="pending"&&data.role==="customer"&&<form action={decisionAction} className="mt-4 space-y-2"><input type="hidden" name="projectId" value={data.project.id}/><input type="hidden" name="changeOrderId" value={change.id}/><textarea name="comment" className="min-h-20 w-full rounded-xl border bg-background p-3" placeholder="Комментарий к решению"/><div className="flex flex-wrap gap-2"><button disabled={decisionPending} name="decision" value="approved" className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Согласовать</button><button disabled={decisionPending} name="decision" value="rejected" className="rounded-xl border px-4 py-2 text-red-700">Отклонить</button></div></form>}{change.status==="pending"&&data.role==="contractor"&&change.requestedByCurrentUser&&<form action={cancelAction} className="mt-3"><input type="hidden" name="projectId" value={data.project.id}/><input type="hidden" name="changeOrderId" value={change.id}/><button className="text-sm font-semibold text-red-600">Отменить запрос</button></form>}</article>)}</div><ActionMessage state={decisionState??cancelState}/></section>

   {data.payments.length>0&&<section className="rounded-[1.75rem] border border-border bg-card p-5"><h2 className="text-xl font-black">Ручные записи платежей</h2><p className="mt-1 text-sm text-muted-foreground">Архив переходного режима. Онлайн-платежи ЮKassa отображаются непосредственно у соответствующего этапа.</p><div className="mt-4 space-y-3">{data.payments.map(payment=><PaymentCard key={payment.id} payment={payment} projectId={data.project.id} role={data.role} stageTitle={payment.stageId?data.stages.find(stage=>stage.id===payment.stageId)?.title:null}/>)}</div></section>}
  </div>

  <aside className="space-y-5">
   {data.role==="contractor"&&<section className="rounded-[1.75rem] border bg-card p-5"><h2 className="font-black">Запросить изменение договора</h2><p className="mt-1 text-xs text-muted-foreground">Стоимость или срок меняются только после согласования заказчиком.</p><form action={changeAction} className="mt-4 space-y-3"><input type="hidden" name="projectId" value={data.project.id}/><input type="hidden" name="idempotencyKey" value={changeKey}/><Field name="title" placeholder="Название изменения" required/><textarea name="reason" required placeholder="Почему изменение необходимо" className="min-h-20 w-full rounded-xl border bg-background p-3"/><textarea name="scopeChange" required placeholder="Что именно меняется" className="min-h-24 w-full rounded-xl border bg-background p-3"/><Field name="amountDelta" type="number" step="0.01" defaultValue="0" required/><Field name="durationDeltaDays" type="number" defaultValue="0" required/><button disabled={changePending} className="min-h-11 w-full rounded-xl bg-primary text-sm font-bold text-primary-foreground">Отправить на согласование</button></form><ActionMessage state={changeState}/></section>}

   {data.role==="customer"&&!data.paymentsEnabled&&<section className="rounded-[1.75rem] border bg-card p-5"><h2 className="font-black">Ручной учёт принятого этапа</h2><p className="mt-1 text-xs text-muted-foreground">Доступен только пока платёжный провайдер отключён. Записать можно только выплату по этапу, уже принятому заказчиком.</p><form action={paymentAction} className="mt-4 space-y-3"><input type="hidden" name="projectId" value={data.project.id}/><input type="hidden" name="idempotencyKey" value={paymentKey}/><select name="stageId" required className="min-h-11 w-full rounded-xl border bg-background px-3"><option value="">Выберите принятый этап</option>{data.stages.filter(stage=>stage.status==="completed"&&stage.remainingAmount>0).map(stage=><option key={stage.id} value={stage.id}>{stage.title} — {money(stage.remainingAmount)}</option>)}</select><Field name="amount" type="number" step="0.01" min="0.01" max={data.project.remaining} placeholder="Сумма, ₽" required/><Field name="paidAt" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><textarea name="note" placeholder="Комментарий" className="min-h-20 w-full rounded-xl border bg-background p-3"/><button disabled={paymentPending} className="min-h-11 w-full rounded-xl bg-secondary text-sm font-bold">Добавить запись</button></form><ActionMessage state={paymentState}/></section>}
  </aside></div>
 </div></main>;
}

function StagePaymentCard({stage,projectId,role,paymentsEnabled}:{stage:Stage;projectId:string;role:"customer"|"contractor";paymentsEnabled:boolean}){
 const intent=stage.paymentIntent;const info=providerPaymentStatus(intent?.status??null,stage.status);
 const canCreate=role==="customer"&&paymentsEnabled&&!intent&&stage.plannedAmount>0;
 return <article className="rounded-2xl border border-border p-4 md:p-5"><div className="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><p className="break-words font-bold">{stage.title}</p><p className="mt-1 text-xs text-muted-foreground">{stageStatus(stage.status)} · вес {stage.progressWeight}%</p><div className={`mt-3 inline-flex max-w-full items-center rounded-full px-3 py-1.5 text-xs font-bold ${info.className}`}>{info.label}</div>{intent?.failureReason&&<p className="mt-2 break-words text-xs text-red-700">{intent.failureReason}</p>}</div><div className="shrink-0 lg:text-right"><strong>{money(stage.paidAmount)} / {money(stage.plannedAmount)}</strong><p className="text-xs text-muted-foreground">заказчику осталось внести {money(stage.remainingAmount)}</p></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-primary" style={{width:`${stage.paymentProgress}%`}}/></div>
 {canCreate&&<StagePaymentButton projectId={projectId} stageId={stage.id}/>} 
 {role==="customer"&&paymentsEnabled&&intent?.status==="awaiting_payment"&&intent.confirmationUrl&&<Link href={intent.confirmationUrl} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-bold text-primary-foreground"><CreditCard className="h-4 w-4"/>Продолжить оплату</Link>}
 {intent&&["funded","stage_submitted"].includes(intent.status)&&<p className="mt-3 rounded-xl bg-blue-50 p-3 text-xs text-blue-900">Деньги зарезервированы у платёжного провайдера. Выплата подрядчику заблокирована до приёмки этого этапа заказчиком.</p>}
 {intent?.status==="release_ready"&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-900">Этап принят заказчиком. Выплата разрешена и будет обработана системой.</p>}
 </article>;
}

function PaymentCard({payment,projectId,role,stageTitle}:{payment:Payment;projectId:string;role:"customer"|"contractor";stageTitle:string|null|undefined}){
 const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();const [reason,setReason]=useState("");const status=payment.confirmationStatus;
 function confirm(){setMessage("");startTransition(async()=>{const result=await confirmProjectPayment({paymentId:payment.id,projectId});setMessage(result.message)})}
 function dispute(){if(reason.trim().length<5){setMessage("Укажите причину спора минимум из 5 символов");return}setMessage("");startTransition(async()=>{const result=await disputeProjectPayment({paymentId:payment.id,projectId,reason});setMessage(result.message)})}
 function cancel(){if(reason.trim().length<5){setMessage("Укажите причину отмены минимум из 5 символов");return}setMessage("");startTransition(async()=>{const result=await cancelProjectPaymentConfirmation({paymentId:payment.id,projectId,reason});setMessage(result.message)})}
 return <article className="rounded-xl border p-4"><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="font-semibold">{formatDate(payment.paidAt)}</p>{stageTitle&&<p className="break-words text-xs text-muted-foreground">{stageTitle}</p>}{payment.note&&<p className="mt-1 break-words text-sm text-muted-foreground">{payment.note}</p>}<PaymentStatus payment={payment}/></div><strong className="shrink-0">{money(payment.amount)}</strong></div>{status!=="cancelled"&&status!=="disputed"&&<div className="mt-4 rounded-xl bg-secondary/35 p-3"><div className="grid gap-2 sm:grid-cols-2"><span className="text-xs font-semibold">Заказчик: {payment.customerConfirmedAt?"подтверждено":"ожидается"}</span><span className="text-xs font-semibold">Подрядчик: {payment.contractorConfirmedAt?"подтверждено":"ожидается"}</span></div>{!payment.currentUserConfirmed&&status!=="confirmed"&&<button disabled={pending} onClick={confirm} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-bold text-primary-foreground"><CheckCircle2 className="h-4 w-4"/>Подтвердить запись</button>}</div>}{status==="disputed"&&payment.disputeReason&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">Причина спора: {payment.disputeReason}</p>}{status!=="confirmed"&&status!=="cancelled"&&<div className="mt-3"><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} placeholder={role==="customer"?"Причина спора или отмены":"Причина спора"} className="min-h-20 w-full rounded-xl border bg-background p-2 text-sm"/><div className="mt-2 flex flex-wrap gap-2"><button disabled={pending} onClick={dispute} className="inline-flex min-h-9 items-center gap-2 rounded-xl border border-red-200 px-3 text-xs font-semibold text-red-700"><ShieldAlert className="h-4 w-4"/>Оспорить</button>{role==="customer"&&<button disabled={pending} onClick={cancel} className="inline-flex min-h-9 items-center gap-2 rounded-xl border px-3 text-xs font-semibold text-muted-foreground"><XCircle className="h-4 w-4"/>Отменить запись</button>}</div></div>}{message&&<p className="mt-3 text-xs font-semibold">{message}</p>}</article>;
}

function providerPaymentStatus(status:string|null,stageStatus:string){if(!status)return{label:"Оплата не создана",className:"bg-secondary text-muted-foreground"};const map:Record<string,{label:string;className:string}>={planned:{label:"Подготовка платежа",className:"bg-secondary text-foreground"},awaiting_payment:{label:"Ожидает оплаты заказчиком",className:"bg-amber-50 text-amber-800"},funded:{label:"Деньги зарезервированы",className:"bg-blue-50 text-blue-800"},stage_submitted:{label:"Этап на приёмке — выплата заблокирована",className:"bg-blue-50 text-blue-800"},release_ready:{label:"Этап принят — выплата разрешена",className:"bg-emerald-50 text-emerald-800"},payout_processing:{label:"Выплата обрабатывается",className:"bg-violet-50 text-violet-800"},paid:{label:"Выплачено подрядчику",className:"bg-emerald-50 text-emerald-800"},disputed:{label:"Платёж приостановлен из-за спора",className:"bg-red-50 text-red-800"},refund_pending:{label:"Возврат обрабатывается",className:"bg-amber-50 text-amber-800"},refunded:{label:"Деньги возвращены заказчику",className:"bg-secondary text-foreground"},cancelled:{label:"Платёж отменён",className:"bg-secondary text-muted-foreground"}};return map[status]??{label:`Статус платежа: ${status}`,className:"bg-secondary text-foreground"}}
function PaymentStatus({payment}:{payment:Payment}){const status=payment.confirmationStatus;const label=status==="confirmed"?"Подтверждено обеими сторонами":status==="disputed"?"Оспорено":status==="cancelled"?"Отменено":"Ожидает подтверждения";return <p className="mt-2 text-xs font-bold text-muted-foreground">{label}</p>}
function Status({status}:{status:string}){const labels:Record<string,string>={pending:"Ожидает согласования",approved:"Согласовано",rejected:"Отклонено",cancelled:"Отменено"};return <span className="text-xs font-bold text-primary">{labels[status]??status}</span>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className="min-h-11 w-full rounded-xl border bg-background px-3 text-sm"/>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-[1.5rem] border bg-card p-5"><div className="text-primary">{icon}</div><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-2 break-words text-xl font-black">{value}</p></div>}
function ActionMessage({state}:{state:Result}){return state?<p className={`mt-3 text-xs font-semibold ${state.success?"text-emerald-700":"text-red-700"}`}>{state.message}</p>:null}
function stageStatus(value:string){return({planned:"Запланирован",in_progress:"В работе",awaiting_review:"На приёмке",revision_required:"Требует доработки",completed:"Принят заказчиком"} as Record<string,string>)[value]??value}
function money(value:number){return new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(value)}
function signedMoney(value:number){return `${value>0?"+":""}${money(value)}`}
function formatDate(value:string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium"}).format(new Date(value))}
function formatDateTime(value:string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
